UCSC:focus on the database of mammalian genomes;
Entrez:easy to operate and have so many data, but have less information of each data unless there are some unknown function to me;
KEGG:easy to find the pathway of many species, especially prokaryotic species.
Reactome:show me a lot of pathway.
I like KEGG more, because it has a lot of prokaryotic species and pathway is appeared to be clear. But I think Reactome is also cool because it feels fancy to operate.

In [31]:
import sqlite3
lab4 = sqlite3.connect('lab4.db')

### 1. create a table for genes

In [32]:
lab = lab4.cursor()
lab.execute("""CREATE TABLE genes(id INT,
                                name TEXT,
                                description TEXT,
                                organism TEXT,
                                nucleotide_sequence TEXT,
                                chromosome TEXT,
                                start INT,
                                end INT,
                                aa TEXT);""")

#### 1.1 Gene in Pentose phosphate pathway
       1.1.1 Homo Sapiens                
       1.1.2 Drosophila melanogaster
       1.1.3 Escherichia coli

##### 1.1.1 Homo Sapiens
       https://www.genome.jp/dbget-bin/www_bget?hsa:5226
       https://www.ncbi.nlm.nih.gov/nuccore/NC_000001.11?report=genbank&from=10399064&to=10420511
       https://www.ncbi.nlm.nih.gov/gene/5226

In [33]:
lab = lab4.cursor()
lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(1,
                                'G6PD',
                                'glucose-6-phosphate dehydrogenase',
                                'Homo Sapiens',
                                'atggcagagcaggtggccctgagccggacccaggtgtgcgggatcctgcgggaagagcttttccagggcgatgccttccatcagtcggatacacacatattcatcatcatgggtgcatcgggtgacctggccaagaagaagatctaccccaccatctggtggctgttccgggatggccttctgcccgaaaacaccttcatcgtgggctatgcccgttcccgcctcacagtggctgacatccgcaaacagagtgagcccttcttcaaggccaccccagaggagaagctcaagctggaggacttctttgcccgcaactcctatgtggctggccagtacgatgatgcagcctcctaccagcgcctcaacagccacatgaatgccctccacctggggtcacaggccaaccgcctcttctacctggccttgcccccgaccgtctacgaggccgtcaccaagaacattcacgagtcctgcatgagccagataggctggaaccgcatcatcgtggagaagcccttcgggagggacctgcagagctctgaccggctgtccaaccacatctcctccctgttccgtgaggaccagatctaccgcatcgaccactacctgggcaaggagatggtgcagaacctcatggtgctgagatttgccaacaggatcttcggccccatctggaaccgggacaacatcgcctgcgttatcctcaccttcaaggagccctttggcactgagggtcgcgggggctatttcgatgaatttgggatcatccgggacgtgatgcagaaccacctactgcagatgctgtgtctggtggccatggagaagcccgcctccaccaactcagatgacgtccgtgatgagaaggtcaaggtgttgaaatgcatctcagaggtgcaggccaacaatgtggtcctgggccagtacgtggggaaccccgatggagagggcgaggccaccaaagggtacctggacgaccccacggtgccccgcgggtccaccaccgccacttttgcagccgtcgtcctctatgtggagaatgagaggtgggatggggtgcccttcatcctgcgctgcggcaaggccctgaacgagcgcaaggccgaggtgaggctgcagttccatgatgtggccggcgacatcttccaccagcagtgcaagcgcaacgagctggtgatccgcgtgcagcccaacgaggccgtgtacaccaagatgatgaccaagaagccgggcatgttcttcaaccccgaggagtcggagctggacctgacctacggcaacagatacaagaacgtgaagctccctgacgcctatgagcgcctcatcctggacgtcttctgcgggagccagatgcacttcgtgcgcagcgacgagctccgtgaggcctggcgtattttcaccccactgctgcaccagattgagctggagaagcccaagcccatcccctatatttatggcagccgaggccccacggaggcagacgagctgatgaagagagtgggtttccagtatgagggcacctacaagtgggtgaacccccacaagctctga',
                                'Xq28',
                                154531390,
                                154547569,
                                'MAEQVALSRTQVCGILREELFQGDAFHQSDTHIFIIMGASGDLAKKKIYPTIWWLFRDGLLPENTFIVGYARSRLTVADIRKQSEPFFKATPEEKLKLEDFFARNSYVAGQYDDAASYQRLNSHMNALHLGSQANRLFYLALPPTVYEAVTKNIHESCMSQIGWNRIIVEKPFGRDLQSSDRLSNHISSLFREDQIYRIDHYLGKEMVQNLMVLRFANRIFGPIWNRDNIACVILTFKEPFGTEGRGGYFDEFGIIRDVMQNHLLQMLCLVAMEKPASTNSDDVRDEKVKVLKCISEVQANNVVLGQYVGNPDGEGEATKGYLDDPTVPRGSTTATFAAVVLYVENERWDGVPFILRCGKALNERKAEVRLQFHDVAGDIFHQQCKRNELVIRVQPNEAVYTKMMTKKPGMFFNPEESELDLTYGNRYKNVKLPDAYERLILDVFCGSQMHFVRSDELREAWRIFTPLLHQIELEKPKPIPYIYGSRGPTEADELMKRVGFQYEGTYKWVNPHKL');""")

lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(2,
                                'GPI',
                                'glucose-6-phosphate isomerase',
                                'Homo Sapiens',
                                'atggccgctctcacccgggacccccagttccagaagctgcagcaatggtaccgcgagcaccgctccgagctgaacctgcgccgcctcttcgatgccaacaaggaccgcttcaaccacttcagcttgaccctcaacaccaaccatgggcatatcctggtggattactccaagaacctggtgacggaggacgtgatgcggatgctggtggacttggccaagtccaggggcgtggaggccgcccgggagcggatgttcaatggtgagaagatcaactacaccgagggtcgagccgtgctgcacgtggctctgcggaaccggtcaaacacacccatcctggtagacggcaaggatgtgatgccagaggtcaacaaggttctggacaagatgaagtctttctgccagcgtgtccggagcggtgactggaaggggtacacaggcaagaccatcacggacgtcatcaacattggcattggcggctccgacctgggacccctcatggtgactgaagcccttaagccatactcttcaggaggtccccgcgtctggtatgtctccaacattgatggaactcacattgccaaaaccctggcccagctgaaccccgagtcctccctgttcatcattgcctccaagacctttactacccaggagaccatcacgaatgcagagacggcgaaggagtggtttctccaggcggccaaggatccttctgcagtggcgaagcactttgttgccctgtctactaacacaaccaaagtgaaggagtttggaattgaccctcaaaacatgttcgagttctgggattgggtgggaggacgctactcgctgtggtcggccatcggactctccattgccctgcacgtgggttttgacaacttcgagcagctgctctcgggggctcactggatggaccagcacttccgcacgacgcccctggagaagaacgcccccgtcttgctggccctgctgggtatctggtacatcaactgctttgggtgtgagacacacgccatgctgccctatgaccagtacctgcaccgctttgctgcgtacttccagcagggcgacatggagtccaatgggaaatacatcaccaaatctggaacccgtgtggaccaccagacaggccccattgtgtggggggagccagggaccaatggccagcatgctttttaccagctcatccaccaaggcaccaagatgataccctgtgacttcctcatcccggtccagacccagcaccccatacggaagggtctgcatcacaagatcctcctggccaacttcttggcccagacagaggccctgatgaggggaaaatcgacggaggaggcccgaaaggagctccaggctgcgggcaagagtccagaggaccttgagaggctgctgccacataaggtctttgaaggaaatcgcccaaccaactctattgtgttcaccaagctcacaccattcatgcttggagccttggtcgccatgtatgagcacaagatcttcgttcagggcatcatctgggacatcaacagctttgaccagtggggagtggagctgggaaagcagctggctaagaaaatagagcctgagcttgatggcagtgctcaagtgacctctcacgacgcttctaccaatgggctcatcaacttcatcaagcagcagcgcgaggccagagtccaataa',
                                '19q13.11',
                                34353330,
                                34402413,
                                'MAALTRDPQFQKLQQWYREHRSELNLRRLFDANKDRFNHFSLTLNTNHGHILVDYSKNLVTEDVMRMLVDLAKSRGVEAARERMFNGEKINYTEGRAVLHVALRNRSNTPILVDGKDVMPEVNKVLDKMKSFCQRVRSGDWKGYTGKTITDVINIGIGGSDLGPLMVTEALKPYSSGGPRVWYVSNIDGTHIAKTLAQLNPESSLFIIASKTFTTQETITNAETAKEWFLQAAKDPSAVAKHFVALSTNTTKVKEFGIDPQNMFEFWDWVGGRYSLWSAIGLSIALHVGFDNFEQLLSGAHWMDQHFRTTPLEKNAPVLLALLGIWYINCFGCETHAMLPYDQYLHRFAAYFQQGDMESNGKYITKSGTRVDHQTGPIVWGEPGTNGQHAFYQLIHQGTKMIPCDFLIPVQTQHPIRKGLHHKILLANFLAQTEALMRGKSTEEARKELQAAGKSPEDLERLLPHKVFEGNRPTNSIVFTKLTPFMLGALVAMYEHKIFVQGIIWDINSFDQWGVELGKQLAKKIEPELDGSAQVTSHDASTNGLINFIKQQREARVQ');""")

lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(3,
                                'H6PD',
                                'hexose-6-phosphate dehydrogenase/glucose 1-dehydrogenase',
                                'Homo Sapiens',
                                '1p36.22',
                                'atgtggaatatgctcatagtggcgatgtgcttggcccttctgggctgcctgcaagcccaggagctccagggacatgtctccataatcctgctgggagcaactggggacctggctaagaagtacttatggcagggactgttccagctgtacctggatgaagcggggaggggtcacagttttagcttccatggagctgctctgacagcccccaagcagggtcaagagctcatggccaaggccctggaatccctctcctgccccaaggacatggcacccagtcactgtgcagagcacaaggatcagttcctgcagctgagccagtaccgccaactgaagacggccgaggactatcaggccctgaacaaggacatcgaggcacagctccagcacgcaggcctccgggaggctggcaggatcttctacttctcagtgccacccttcgcctatgaagacattgcccgcaacatcaacagtagctgccggccaggcccgggcgcctggctgcgggttgtccttgagaaaccctttggccatgaccacttctcagcccagcagctggccacagaactcgggacctttttccaggaggaggagatgtaccgggtggaccattacttaggcaagcaggctgtggcgcagatcctgcctttccgagaccagaaccgcaaggctttggacggcctctggaaccggcaccatgtggagcgggtggagatcatcatgaaagagaccgtggatgctgaaggccgcaccagcttctatgaggagtacggtgtcattcgcgacgtcctccagaaccatctgacggaggtcctcaccctcgtggccatggagctgccccacaatgtcagcagtgcggaggctgtgctgcggcacaagcttcaggtcttccaggcgctgcggggcctgcagaggggcagtgccgtcgtgggccagtaccagtcttacagtgagcaggtgcgcagagagctgcagaagccagacagcttccacagcctgacgccgaccttcgcagccgtcctagtgcacattgacaaccttcgctgggagggcgtgcctttcatcctgatgtctggcaaagccttggacgagagagtgggctacgctcggatcttgttcaagaaccaggcctgctgtgtgcagagcgaaaagcactgggccgcggcgcagagccagtgcctgccccggcagctcgtcttccacatcggccatggcgacctgggcagccctgccgtgctggtcagcaggaacctgttcaggccctccctgccctccagctggaaggaaatggagggaccacctgggctccgccttttcggcagccctctgtccgattactacgcctacagccctgtgcgggagcgggacgcccactccgtcctcttatcccatatcttccatggccggaagaatttcttcatcaccacagagaacttgctggcctcctggaacttctggacccctctgctggagagcctggcccataaggccccacgcctctaccctggaggagctgagaatggccgtctgttggactttgagttcagtagcggccggttgttcttttcccagcagcagccggagcagctggtgccagggccagggccggccccaatgcccagtgacttccaggtcctcagggccaagtaccgagagagcccgctggtctccgcctggtccgaggagctgatctctaagctggctaatgacatcgaggccaccgctgtgcgagccgtgcggcgctttggccagttccacctggcactgtcggggggctcgagccccgtggccctgttccagcagctggccacggcgcactatggcttcccctgggcccacacgcacctgtggctggttgacgagcgctgcgtcccactctcagacccggagtccaacttccagggcctgcaggcccacctgctgcagcacgtccggatcccctactacaacatccaccccatgcctgtgcacctgcagcagcggctctgcgccgaggaggaccagggcgcccagatctatgccagggagatctcagccctggtggccaacagcagcttcgacctggtgctgctgggcatgggtgccgacgggcacacagcctccctcttcccacagtcacccactggcctggatggcgagcagctggtcgtgctgaccacgagcccctcccagccacaccgccgcatgagccttagcctgcctctcatcaaccgcgccaagaaggtggcagtcctggtcatgggcaggatgaagcgtgagatcaccacgctggtgagccgggtgggccatgagcccaagaagtggcccatctcgggtgtcctgccgcactccggccagctggtgtggtacatggactacgacgccttcctgggatga',
                                9234767,
                                9271337,
                                'MWNMLIVAMCLALLGCLQAQELQGHVSIILLGATGDLAKKYLWQGLFQLYLDEAGRGHSFSFHGAALTAPKQGQELMAKALESLSCPKDMAPSHCAEHKDQFLQLSQYRQLKTAEDYQALNKDIEAQLQHAGLREAGRIFYFSVPPFAYEDIARNINSSCRPGPGAWLRVVLEKPFGHDHFSAQQLATELGTFFQEEEMYRVDHYLGKQAVAQILPFRDQNRKALDGLWNRHHVERVEIIMKETVDAEGRTSFYEEYGVIRDVLQNHLTEVLTLVAMELPHNVSSAEAVLRHKLQVFQALRGLQRGSAVVGQYQSYSEQVRRELQKPDSFHSLTPTFAAVLVHIDNLRWEGVPFILMSGKALDERVGYARILFKNQACCVQSEKHWAAAQSQCLPRQLVFHIGHGDLGSPAVLVSRNLFRPSLPSSWKEMEGPPGLRLFGSPLSDYYAYSPVRERDAHSVLLSHIFHGRKNFFITTENLLASWNFWTPLLESLAHKAPRLYPGGAENGRLLDFEFSSGRLFFSQQQPEQLVPGPGPAPMPSDFQVLRAKYRESPLVSAWSEELISKLANDIEATAVRAVRRFGQFHLALSGGSSPVALFQQLATAHYGFPWAHTHLWLVDERCVPLSDPESNFQGLQAHLLQHVRIPYYNIHPMPVHLQQRLCAEEDQGAQIYAREISALVANSSFDLVLLGMGADGHTASLFPQSPTGLDGEQLVVLTTSPSQPHRRMSLSLPLINRAKKVAVLVMGRMKREITTLVSRVGHEPKKWPISGVLPHSGQLVWYMDYDAFLG');""")

lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(4,
                                'PGD',
                                '6-phosphogluconate dehydrogenase',
                                'Homo Sapiens',
                                'atggcccaagctgacatcgcgctgatcggattggccgtcatgggccagaacttaattctgaacatgaatgaccacggctttgtggtctgtgcttttaataggactgtctccaaagttgatgatttcttggccaatgaggcaaagggaaccaaagtggtgggtgcccagtccctgaaagagatggtctccaagctgaagaagccccggcggatcatcctcctggtgaaggctgggcaagctgtggatgatttcatcgagaaattggtaccattgttggatactggtgacatcatcattgacggaggaaattctgaatatagggacaccacaagacggtgccgagacctcaaggccaagggaattttatttgtggggagcggagtcagtggtggagaggaaggggcccggtatggcccatcgctcatgccaggagggaacaaagaagcgtggccccacatcaagaccatcttccaaggcattgctgcaaaagtgggaactggagaaccctgctgtgactgggtgggagatgagggagcaggccacttcgtgaagatggtgcacaacgggatagagtatggggacatgcagctgatctgtgaggcataccacctgatgaaagacgtgctgggcatggcgcaggacgagatggcccaggcctttgaggattggaataagacagagctagactcattcctgattgaaatcacagccaatattctcaagttccaagacaccgatggcaaacacctgctgccaaagatcagggacagcgcggggcagaagggcacagggaagtggaccgccatctccgccctggaatacggcgtacccgtcaccctcattggagaagctgtctttgctcggtgcttatcatctctgaaggatgagagaattcaagctagcaaaaagctgaagggtccccagaagttccagtttgatggtgataagaaatcattcctggaggacattcggaaggcactctacgcttccaagatcatctcttacgctcaaggctttatgctgctaaggcaggcagccaccgagtttggctggactctcaattatggtggcatcgccctgatgtggagagggggctgcatcattagaagtgtattcctaggaaagataaaggatgcatttgatcgaaacccggaacttcagaacctcctactggacgacttctttaagtcagctgttgaaaactgccaggactcctggcggcgggcagtcagcactggggtccaggctggcattcccatgccctgttttaccactgccctctccttctatgacgggtacagacatgagatgcttccagccagcctcatccaggctcagcgggattacttcggggctcacacctatgaactcttggccaaaccagggcagtttatccacaccaactggacaggccatggtggcaccgtgtcatcctcgtcatacaatgcctga',
                                '1p36.22',
                                10399064,
                                10420511,
                                'MAQADIALIGLAVMGQNLILNMNDHGFVVCAFNRTVSKVDDFLANEAKGTKVVGAQSLKEMVSKLKKPRRIILLVKAGQAVDDFIEKLVPLLDTGDIIIDGGNSEYRDTTRRCRDLKAKGILFVGSGVSGGEEGARYGPSLMPGGNKEAWPHIKTIFQGIAAKVGTGEPCCDWVGDEGAGHFVKMVHNGIEYGDMQLICEAYHLMKDVLGMAQDEMAQAFEDWNKTELDSFLIEITANILKFQDTDGKHLLPKIRDSAGQKGTGKWTAISALEYGVPVTLIGEAVFARCLSSLKDERIQASKKLKGPQKFQFDGDKKSFLEDIRKALYASKIISYAQGFMLLRQAATEFGWTLNYGGIALMWRGGCIIRSVFLGKIKDAFDRNPELQNLLLDDFFKSAVENCQDSWRRAVSTGVQAGIPMPCFTTALSFYDGYRHEMLPASLIQAQRDYFGAHTYELLAKPGQFIHTNWTGHGGTVSSSSYNA');""")

lab4.commit()

##### 1.1.2 Drosophila melanogaster
1.1.2.1
https://www.genome.jp/dbget-bin/www_bget?dme:Dmel_CG12529+dme:Dmel_CG7140
https://www.ncbi.nlm.nih.gov/gene/32974
https://www.ncbi.nlm.nih.gov/nuccore/NC_004354.4?report=genbank&from=19667252&to=19672353
1.1.2.2
https://www.genome.jp/dbget-bin/www_bget?dme:Dmel_CG8251
https://www.ncbi.nlm.nih.gov/gene/35886
https://www.ncbi.nlm.nih.gov/nuccore/NT_033778.4?report=genbank&from=8910900&to=8914069&strand=true
1.1.2.3
https://www.genome.jp/dbget-bin/www_bget?dme:Dmel_CG17333
https://www.ncbi.nlm.nih.gov/gene/32013
https://www.ncbi.nlm.nih.gov/nuccore/NC_004354.4?report=genbank&from=10847438&to=10848534
1.1.2.4
https://www.ncbi.nlm.nih.gov/gene/31185
https://www.ncbi.nlm.nih.gov/nuccore/NC_000001.11?report=genbank&from=10399064&to=10420511
https://www.ncbi.nlm.nih.gov/gene/5226

In [34]:
lab = lab4.cursor()
lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(5,
                                'Zw',
                                'glucose-6-phosphate dehydrogenase',
                                'Drosophila melanogaster',
                                'atggcaacgcaaaaggaagatcacaccgccctggatctcataatcaagtcactcaagtcgcctacaatggtctgcgagggaacccactttgacggcaagattccgcacacgttcgtcatctttggggcgtcgggcgatctggccaagaagaagatctaccccacgctctggtggctctaccgcgatgacctgctgcccaagccgaccaagttctgcggctatgcccgttccatgctgaccgtcgatagcatcaaggagcagtgtctgccgtacatgaaggtccagccgcacgagcagaagaagtacgaggagttctgggccctcaatgagtacgtgtccggcagatatgacggacgcactggcttcgagctgcttaaccagcagctggagattatggagaacaagaacaaggccaaccgcatcttctatctggccctgccgcccagcgtcttcgaggaggtgactgtcaacatcaagcagatctgcatgtcggtctgcggttggaaccgcgtgattatcgagaagcctttcggccgggatgacgcctcctcgcaggcgctgagcgaccatctggccggtctgttccaggaggatcagctgtaccgcatcgatcactacctgggcaaggagatggtgcagaacctgatgaccatacgcttcggcaacaagatcctcagctcgacgtggaaccgcgagaacatcgcctccgtgctgatcacgttcaaggagcccttcggcacgcagggtcgtggcggctacttcgacgagttcggcatcatacgcgacgtgatgcagaaccatctgctgcagatcctctcgctggtggccatggagaagccggtgagctgccacccggacgacattcgtgacgagaaggtcaaggtgctgaagagcatcgaggccctgacgctggatgacatggtgctgggccagtacctgggcaatccgcagggtacaaacgatgatgcgcgcacgggctacgtggaggaccccaccgttagcaacgattcgaacacgcccacctacgccctcggcgtgctcaagatcaacaacgagcgctggcagggagtgcccttcatcctgcgctgcggcaaggcgctgaacgagcgcaaggcggaggtgcgtatccagtaccaggacgtgcccggcgacatcttcgagggcaatacgaagcgcaacgagctggtcatccgcgtccagccgggcgaggccctgtactttaagatgatgaccaagagccccggcatcacgttcgacatcgaggagacggagctggacctcacctacgagcaccgctacaaggactcctacctgccggacgcgtacgagcgtctcatcctcgacgtcttctgcggctcccagatgcacttcgtccgctcggacgagctgcgcgaggcgtggcgcatatttacgcccattctgcaccagatcgagaaggagcacattcggccaatcacctaccagtacggatcgcgcggtcccaaggaggcggaccgcaagtgcgaggagaacaatttcaagtactccggctcctacaagtggcacggcggcaaggcggccacgtccaatcactga',
                                'X',
                                19667252,
                                19672353,
                                'MATQKEDHTALDLIIKSLKSPTMVCEGTHFDGKIPHTFVIFGASGDLAKKKIYPTLWWLYRDDLLPKPTKFCGYARSMLTVDSIKEQCLPYMKVQPHEQKKYEEFWALNEYVSGRYDGRTGFELLNQQLEIMENKNKANRIFYLALPPSVFEEVTVNIKQICMSVCGWNRVIIEKPFGRDDASSQALSDHLAGLFQEDQLYRIDHYLGKEMVQNLMTIRFGNKILSSTWNRENIASVLITFKEPFGTQGRGGYFDEFGIIRDVMQNHLLQILSLVAMEKPVSCHPDDIRDEKVKVLKSIEALTLDDMVLGQYLGNPQGTNDDARTGYVEDPTVSNDSNTPTYALGVLKINNERWQGVPFILRCGKALNERKAEVRIQYQDVPGDIFEGNTKRNELVIRVQPGEALYFKMMTKSPGITFDIEETELDLTYEHRYKDSYLPDAYERLILDVFCGSQMHFVRSDELREAWRIFTPILHQIEKEHIRPITYQYGSRGPKEADRKCEENNFKYSGSYKWHGGKAATSNH');""")



lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(6,
                                'pgi',
                                'glucose-6-phosphate isomerase',
                                'Drosophila melanogaster',
                                'atggccggcccacttcctccgctcaaccaggaggcagcgttccagaagctgcaggagtactacgactccaagggcaaggacctgaacatcaaggacctgttcgtgaaggattccaagagattctcaaaatacagcctgcgcctgcacacccagaacgatggcgagatactgctggactactcgaagaaccgtatcaatgacgaggtctgggatctgctcctcaccctggccaaggtgcgccgcgttaacgccgcgcgggacgccatgttctccggccagcacattaacatcacggagaaccgcgccgtcctccacacggccctgcgcaaccgcggcacggatcccgtcctggtggacgacaaggacgtgatgcccgatgtgcgcgccgaactggcccacatgaaggagttcaccaacatggtcatctccggcgtgtggcgcggctgcaccggcaaacagatcaccgacgtggtcaacatcggcatcggtggctccgatctgggcccgctgatggtcaccgaagcgctgaagccctacggcaagggccttcactcccactttgtgtcgaacatcgatggcactcatctggccgaggtcctcaagaaggtcaactacgagaccaccctcttcattgtcgcctcaaaaactttcaccacccaggagaccattacgaacgccacctccgccaagacctggctcctggagcattccaaggagcctgagtccgtggccaagcattttgtggccctgtcgaccaacaaggaaaaggtcaccgaattcggcattgacagcaccaacatgttcggtttttgggattgggtgggcggtcgctactccctgtggtcggccattggactgtcaatctgtctgtccattggctttgagaactttgagcaactgctggatggagctcacttcatggacaaccatttcaagacgacaccattcgagaagaatgctcctgttatcctggcgttgctaggcgtttggtactccaacttcttcaaggcggaaacacatgccctccttccctacgatcagtacttgcaccggttcgccgcctacttccagcagggcgatatggagagcaacggcaagttcgtcagcaagtcgggcaaacccgtcaagtacagcactggtccgatcgtgtggggcgagcctggcaccaatggccagcacgccttctaccagctcatccaccagggcacccgcctgatcccctgcgatttcatcgctcccgcccagacacacaatcccattgccggcggcaagcaccacaagattctgctatcgaatttccttgcccagacggaggctttaatggccggaaagacggtcgacgaggccaggaccgagctgtccaaggctggcctgtgcggcaacgagctggataacttgttgccccacaaggtgttcgtcggcaaccggcccacaaactcgattgtggtgaagaaggtttcacctttcaccctaggcgcgttgattgcgctgtacgagcacaagatcttcgttcagggcatcatttgggacatcaactcgttcgaccaatggggtgtggagctgggcaagcagctggccaaggccatcgagccggagctggatcactgcaacgaggtctccacgcacgacagttccacgaacggtctaattaacttcatcaaagccaattggaagtaa',
                                '2',
                                8910900,
                                8914069,
                                'MAGPLPPLNQEAAFQKLQEYYDSKGKDLNIKDLFVKDSKRFSKYSLRLHTQNDGEILLDYSKNRINDEVWDLLLTLAKVRRVNAARDAMFSGQHINITENRAVLHTALRNRGTDPVLVDDKDVMPDVRAELAHMKEFTNMVISGVWRGCTGKQITDVVNIGIGGSDLGPLMVTEALKPYGKGLHSHFVSNIDGTHLAEVLKKVNYETTLFIVASKTFTTQETITNATSAKTWLLEHSKEPESVAKHFVALSTNKEKVTEFGIDSTNMFGFWDWVGGRYSLWSAIGLSICLSIGFENFEQLLDGAHFMDNHFKTTPFEKNAPVILALLGVWYSNFFKAETHALLPYDQYLHRFAAYFQQGDMESNGKFVSKSGKPVKYSTGPIVWGEPGTNGQHAFYQLIHQGTRLIPCDFIAPAQTHNPIAGGKHHKILLSNFLAQTEALMAGKTVDEARTELSKAGLCGNELDNLLPHKVFVGNRPTNSIVVKKVSPFTLGALIALYEHKIFVQGIIWDINSFDQWGVELGKQLAKAIEPELDHCNEVSTHDSSTNGLINFIKANWK');""")


lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(7,
                                'CG17333',
                                '6-phosphogluconolactonase',
                                'Drosophila melanogaster',
                                'atgtcggagaaaaagggtgcgctaaaagtaatcccgtccgcttcggaggagcaacttgtccaggccctgggcgatcttctccagcgctgctcccaggaggcgctggccaaacatgataagttcagcgtgggactttcgggtggttccctcgtccagttgctaacgaaagccctgaaatcgtgcaacttaaaaacggccaaatgggtgtttttcttctgtgacgagcggtatgttcgcctggatgacagcgattccacctatggtgcctacagggccgagtggctaacccaattgccctgcatccaggaatcccagttcgtccgcgccgataccagccaaccgctggacgcctgcgccgcagattacgaggcgaaggtcaaaagtcaagtcgatcgcttcgatctgctgctgcttggcatgggacccgatggccacacctgctccctctttcccgagcagccagccaccctgcaggagaccaagcgcctggttatccccatccggaactcgcccaagccgcctcccgagcggatcactttcaccctgccgctgatcaataaggcacggaatgtcgccttcgtggttacgggcgccgcaaaagccagtgtcgtcaagagtgtgtttgtcgatctggacaagaagtttcccgctgcgtgggtgaatccgaccaaagggcagttgacattgattgtggacgcgggtgctggaaaagaaattgaaaccttaaaatga',
                                'X',
                                10847438,
                                10848534,
                                'MSEKKGALKVIPSASEEQLVQALGDLLQRCSQEALAKHDKFSVGLSGGSLVQLLTKALKSCNLKTAKWVFFFCDERYVRLDDSDSTYGAYRAEWLTQLPCIQESQFVRADTSQPLDACAADYEAKVKSQVDRFDLLLLGMGPDGHTCSLFPEQPATLQETKRLVIPIRNSPKPPPERITFTLPLINKARNVAFVVTGAAKASVVKSVFVDLDKKFPAAWVNPTKGQLTLIVDAGAGKEIETLK');""")


lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(8,
                                'Pgd',
                                '6-phosphogluconate dehydrogenase',
                                'Drosophila melanogaster',
                                'atggcccaagctgacatcgcgctgatcggattggccgtcatgggccagaacttaattctgaacatgaatgaccacggctttgtggtctgtgcttttaataggactgtctccaaagttgatgatttcttggccaatgaggcaaagggaaccaaagtggtgggtgcccagtccctgaaagagatggtctccaagctgaagaagccccggcggatcatcctcctggtgaaggctgggcaagctgtggatgatttcatcgagaaattggtaccattgttggatactggtgacatcatcattgacggaggaaattctgaatatagggacaccacaagacggtgccgagacctcaaggccaagggaattttatttgtggggagcggagtcagtggtggagaggaaggggcccggtatggcccatcgctcatgccaggagggaacaaagaagcgtggccccacatcaagaccatcttccaaggcattgctgcaaaagtgggaactggagaaccctgctgtgactgggtgggagatgagggagcaggccacttcgtgaagatggtgcacaacgggatagagtatggggacatgcagctgatctgtgaggcataccacctgatgaaagacgtgctgggcatggcgcaggacgagatggcccaggcctttgaggattggaataagacagagctagactcattcctgattgaaatcacagccaatattctcaagttccaagacaccgatggcaaacacctgctgccaaagatcagggacagcgcggggcagaagggcacagggaagtggaccgccatctccgccctggaatacggcgtacccgtcaccctcattggagaagctgtctttgctcggtgcttatcatctctgaaggatgagagaattcaagctagcaaaaagctgaagggtccccagaagttccagtttgatggtgataagaaatcattcctggaggacattcggaaggcactctacgcttccaagatcatctcttacgctcaaggctttatgctgctaaggcaggcagccaccgagtttggctggactctcaattatggtggcatcgccctgatgtggagagggggctgcatcattagaagtgtattcctaggaaagataaaggatgcatttgatcgaaacccggaacttcagaacctcctactggacgacttctttaagtcagctgttgaaaactgccaggactcctggcggcgggcagtcagcactggggtccaggctggcattcccatgccctgttttaccactgccctctccttctatgacgggtacagacatgagatgcttccagccagcctcatccaggctcagcgggattacttcggggctcacacctatgaactcttggccaaaccagggcagtttatccacaccaactggacaggccatggtggcaccgtgtcatcctcgtcatacaatgcctga',
                                'X',
                                2145136,
                                2148566,
                                'MSGQADIALIGLAVMGQNLILNMDEKGFVVCAYNRTVAKVKEFLANEAKDTKVIGADSLEDMVSKLKSPRKVMLLVKAGSAVDDFIQQLVPLLSAGDVIIDGGNSEYQDTSRRCDELAKLGLLFVGSGVSGGEEGARHGPSLMPGGHEAAWPLIQPIFQAICAKADGEPCCEWVGDGGAGHFVKMVHNGIEYGDMQLICEAYHIMQSLGLSADQMADEFGKWNSAELDSFLIEITRDILKYKDGKGYLLERIRDTAGQKGTGKWTAIAALQYGVPVTLIGEAVFSRCLSALKDERVQASSVLKGPSTKAQVANLTKFLDDIKHALYCAKIVSYAQGFMLMREAARENKWRLNYGGIALMWRGGCIIRSVFLGNIKDAYTSQPELSNLLLDDFFKKAIERGQDSWREVVANAFRWGIPVPALSTALSFYDGYRTAKLPANLLQAQRDYFGAHTYELLGQEGQFHHTNWTGTGGNVSASTYQA');""")

lab4.commit()

##### 1.1.3 Escherichia coli
https://www.genome.jp/dbget-bin/www_bget?eco:b0767
https://www.genome.jp/dbget-bin/www_bget?eco:b2029

In [35]:
lab = lab4.cursor()
lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(9,
                                'Zwf',
                                'glucose-6-phosphate dehydrogenase',
                                'Escherichia coli',
                                'atggcggtaacgcaaacagcccaggcctgtgacctggtcattttcggcgcgaaaggcgaccttgcgcgtcgtaaattgctgccttccctgtatcaactggaaaaagccggtcagctcaacccggacacccggattatcggcgtagggcgtgctgactgggataaagcggcatataccaaagttgtccgcgaggcgctcgaaactttcatgaaagaaaccattgatgaaggtttatgggacaccctgagtgcacgtctggatttttgtaatctcgatgtcaatgacactgctgcattcagccgtctcggcgcgatgctggatcaaaaaaatcgtatcaccattaactactttgccatgccgcccagcacttttggcgcaatttgcaaagggcttggcgaggcaaaactgaatgctaaaccggcacgcgtagtcatggagaaaccgctggggacgtcgctggcgacctcgcaggaaatcaatgatcaggttggcgaatacttcgaggagtgccaggtttaccgtatcgaccactatcttggtaaagaaacggtgctgaacctgttggcgctgcgttttgctaactccctgtttgtgaataactgggacaatcgcaccattgatcatgttgagattaccgtggcagaagaagtggggatcgaagggcgctggggctattttgataaagccggtcagatgcgcgacatgatccagaaccacctgctgcaaattctttgcatgattgcgatgtctccgccgtctgacctgagcgcagacagcatccgcgatgaaaaagtgaaagtactgaagtctctgcgccgcatcgaccgctccaacgtacgcgaaaaaaccgtacgcgggcaatatactgcgggcttcgcccagggcaaaaaagtgccgggatatctggaagaagagggcgcgaacaagagcagcaatacagaaactttcgtggcgatccgcgtcgacattgataactggcgctgggccggtgtgccattctacctgcgtactggtaaacgtctgccgaccaaatgttctgaagtcgtggtctatttcaaaacacctgaactgaatctgtttaaagaatcgtggcaggatctgccgcagaataaactgactatccgtctgcaacctgatgaaggcgtggatatccaggtactgaataaagttcctggccttgaccacaaacataacctgcaaatcaccaagctggatctgagctattcagaaacctttaatcagacgcatctggcggatgcctatgaacgtttgctgctggaaaccatgcgtggtattcaggcactgtttgtacgtcgcgacgaagtggaagaagcctggaaatgggtagactccattactgaggcgtgggcgatggacaatgatgcgccgaaaccgtatcaggccggaacctggggacccgttgcctcggtggcgatgattacccgtgatggtcgttcctggaatgagtttgagtaa',
                                'circular',
                                1934839,
                                1936314,
                                'MATQKEDHTALDLIIKSLKSPTMVCEGTHFDGKIPHTFVIFGASGDLAKKKIYPTLWWLYRDDLLPKPTKFCGYARSMLTVDSIKEQCLPYMKVQPHEQKKYEEFWALNEYVSGRYDGRTGFELLNQQLEIMENKNKANRIFYLALPPSVFEEVTVNIKQICMSVCGWNRVIIEKPFGRDDASSQALSDHLAGLFQEDQLYRIDHYLGKEMVQNLMTIRFGNKILSSTWNRENIASVLITFKEPFGTQGRGGYFDEFGIIRDVMQNHLLQILSLVAMEKPVSCHPDDIRDEKVKVLKSIEALTLDDMVLGQYLGNPQGTNDDARTGYVEDPTVSNDSNTPTYALGVLKINNERWQGVPFILRCGKALNERKAEVRIQYQDVPGDIFEGNTKRNELVIRVQPGEALYFKMMTKSPGITFDIEETELDLTYEHRYKDSYLPDAYERLILDVFCGSQMHFVRSDELREAWRIFTPILHQIEKEHIRPITYQYGSRGPKEADRKCEENNFKYSGSYKWHGGKAATSNH');""")


lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(10,
                                'pgi',
                                'glucose-6-phosphate isomerase',
                                'Escherichia coli',
                                'atgaaaaacatcaatccaacgcagaccgctgcctggcaggcactacagaaacacttcgatgaaatgaaagacgttacgatcgccgatctttttgctaaagacggcgatcgtttttctaagttctccgcaaccttcgacgatcagatgctggtggattactccaaaaaccgcatcactgaagagacgctggcgaaattacaggatctggcgaaagagtgcgatctggcgggcgcgattaagtcgatgttctctggcgagaagatcaaccgcactgaaaaccgcgccgtgctgcacgtagcgctgcgtaaccgtagcaataccccgattttggttgatggcaaagacgtaatgccggaagtcaacgcggtgctggagaagatgaaaaccttctcagaagcgattatttccggtgagtggaaaggttataccggcaaagcaatcactgacgtagtgaacatcgggatcggcggttctgacctcggcccatacatggtgaccgaagctctgcgtccgtacaaaaaccacctgaacatgcactttgtttctaacgtcgatgggactcacatcgcggaagtgctgaaaaaagtaaacccggaaaccacgctgttcttggtagcatctaaaaccttcaccactcaggaaactatgaccaacgcccatagcgcgcgtgactggttcctgaaagcggcaggtgatgaaaaacacgttgcaaaacactttgcggcgctttccaccaatgccaaagccgttggcgagtttggtattgatactgccaacatgttcgagttctgggactgggttggcggccgttactctttgtggtcagcgattggcctgtcgattgttctctccatcggctttgataacttcgttgaactgctttccggcgcacacgcgatggacaagcatttctccaccacgcctgccgagaaaaacctgcctgtactgctggcgctgattggcatctggtacaacaatttctttggtgcggaaactgaagcgattctgccgtatgaccagtatatgcaccgtttcgcggcgtacttccagcagggcaatatggagtccaacggtaagtatgttgaccgtaacggtaacgttgtggattaccagactggcccgattatctggggtgaaccaggcactaacggtcagcacgcgttctaccagctgatccaccagggaaccaaaatggtaccgtgcgatttcatcgctccggctatcacccataacccgctctctgatcatcaccagaaactgctgtctaacttcttcgcccagaccgaagcgctggcgtttggtaaatcccgcgaagtggttgagcaggaatatcgtgatcagggtaaagatccggcaacgcttgactacgtggtgccgttcaaagtattcgaaggtaaccgcccgaccaactccatcctgctgcgtgaaatcactccgttcagcctgggtgcgttgattgcgctgtatgagcacaaaatctttactcagggcgtgatcctgaacatcttcaccttcgaccagtggggcgtggaactgggtaaacagctggcgaaccgtattctgccagagctgaaagatgataaagaaatcagcagccacgatagctcgaccaatggtctgattaaccgctataaagcgtggcgcggttaa',
                                'circular',
                                4233758,
                                4235407,
                                'MKNINPTQTAAWQALQKHFDEMKDVTIADLFAKDGDRFSKFSATFDDQMLVDYSKNRITEETLAKLQDLAKECDLAGAIKSMFSGEKINRTENRAVLHVALRNRSNTPILVDGKDVMPEVNAVLEKMKTFSEAIISGEWKGYTGKAITDVVNIGIGGSDLGPYMVTEALRPYKNHLNMHFVSNVDGTHIAEVLKKVNPETTLFLVASKTFTTQETMTNAHSARDWFLKAAGDEKHVAKHFAALSTNAKAVGEFGIDTANMFEFWDWVGGRYSLWSAIGLSIVLSIGFDNFVELLSGAHAMDKHFSTTPAEKNLPVLLALIGIWYNNFFGAETEAILPYDQYMHRFAAYFQQGNMESNGKYVDRNGNVVDYQTGPIIWGEPGTNGQHAFYQLIHQGTKMVPCDFIAPAITHNPLSDHHQKLLSNFFAQTEALAFGKSREVVEQEYRDQGKDPATLDYVVPFKVFEGNRPTNSILLREITPFSLGALIALYEHKIFTQGVILNIFTFDQWGVELGKQLANRILPELKDDKEISSHDSSTNGLINRYKAWRG');""")

lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(11,
                                'pgl',
                                '6-phosphogluconolactonase',
                                'Escherichia coli',
                                'atgaagcaaacagtttatatcgccagccctgagagccagcaaattcacgtctggaatctgaatcatgaaggcgcactgacgctgacacaggttgtcgatgtgccggggcaggtgcagccgatggtggtcagcccggacaaacgttatctctatgttggtgttcgccctgagtttcgcgtcctggcgtatcgtatcgccccggacgatggcgcactgacctttgccgcagagtctgcgctgccgggtagtccgacgcatatttccaccgatcaccaggggcagtttgtctttgtaggttcttacaatgcgggtaacgtgagcgtaacgcgtctggaagatggcctgccagtgggcgtcgtcgatgtggtcgaggggctggacggttgccattccgccaatatctcaccggacaaccgtacgctgtgggttccggcattaaagcaggatcgcatttgcctgtttacggtcagcgatgatggtcatctcgtggcgcaggaccctgcggaagtgaccaccgttgaaggggccggcccgcgtcatatggtattccatccaaacgaacaatatgcgtattgcgtcaatgagttaaacagctcagtggatgtctgggaactgaaagatccgcacggtaatatcgaatgtgtccagacgctggatatgatgccggaaaacttctccgacacccgttgggcggctgatattcatatcaccccggatggtcgccatttatacgcctgcgaccgtaccgccagcctgattaccgttttcagcgtttcggaagatggcagcgtgttgagtaaagaaggcttccagccaacggaaacccagccgcgcggcttcaatgttgatcacagcggcaagtatctgattgccgccgggcaaaaatctcaccacatctcggtatacgaaattgttggcgagcaggggctactgcatgaaaaaggccgctatgcggtcgggcagggaccaatgtgggtggtggttaacgcacactaa',
                                'circular',
                                798586,
                                799581,
                                'MKQTVYIASPESQQIHVWNLNHEGALTLTQVVDVPGQVQPMVVSPDKRYLYVGVRPEFRVLAYRIAPDDGALTFAAESALPGSPTHISTDHQGQFVFVGSYNAGNVSVTRLEDGLPVGVVDVVEGLDGCHSANISPDNRTLWVPALKQDRICLFTVSDDGHLVAQDPAEVTTVEGAGPRHMVFHPNEQYAYCVNELNSSVDVWELKDPHGNIECVQTLDMMPENFSDTRWAADIHITPDGRHLYACDRTASLITVFSVSEDGSVLSKEGFQPTETQPRGFNVDHSGKYLIAAGQKSHHISVYEIVGEQGLLHEKGRYAVGQGPMWVVVNAH');""")


lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(12,
                                'gnd',
                                '6-phosphogluconate dehydrogenase',
                                'Escherichia coli',
                                'atgtccaagcaacagatcggcgtagtcggtatggcagtgatgggacgcaaccttgcgctcaacatcgaaagccgtggttataccgtctctattttcaaccgttcccgtgagaagacggaagaagtgattgccgaaaatccaggcaagaaactggttccttactatacggtgaaagagtttgtcgaatctctggaaacgcctcgtcgcatcctgttaatggtgaaagcaggtgcaggcacggatgctgctattgattccctcaaaccatatctcgataaaggagacatcatcattgatggtggtaacaccttcttccaggacactattcgtcgtaatcgtgagctttcagcagagggctttaacttcatcggtaccggtgtttctggcggtgaagagggggcgctgaaaggtccttctattatgcctggtggccagaaagaagcctatgaattggtagcaccgatcctgaccaaaatcgccgccgtagctgaagacggtgaaccatgcgttacctatattggtgccgatggcgcaggtcactatgtgaagatggttcacaacggtattgaatacggcgatatgcagctgattgctgaagcctattctctgcttaaaggtggcctgaacctcaccaacgaagaactggcgcagacctttaccgagtggaataacggtgaactgagcagttacctgatcgacatcaccaaagatatcttcaccaaaaaagatgaagacggtaactacctggttgatgtgatcctggatgaagcggctaacaaaggtaccggtaaatggaccagccagagcgcgctggatctcggcgaaccgctgtcgctgattaccgagtctgtgtttgcacgttatatctcttctctgaaagatcagcgtgttgccgcatctaaagttctctctggtccgcaagcacagccagcaggcgacaaggctgagttcatcgaaaaagttcgtcgtgcgctgtatctgggcaaaatcgtttcttacgcccagggcttctctcagctgcgtgctgcgtctgaagagtacaactgggatctgaactacggcgaaatcgcgaagattttccgtgctggctgcatcatccgtgcgcagttcctgcagaaaatcaccgatgcttatgccgaaaatccacagatcgctaacctgttgctggctccgtacttcaagcaaattgccgatgactaccagcaggcgctgcgtgatgtcgttgcttatgcagtacagaacggtattccggttccgaccttctccgcagcggttgcctattacgacagctaccgtgctgctgttctgcctgcgaacctgatccaggcacagcgtgactattttggtgcgcatacttataagcgtattgataaagaaggtgtgttccataccgaatggctggattaa',
                                'circular',
                                2099862,
                                2101268,
                                'MSKQQIGVVGMAVMGRNLALNIESRGYTVSIFNRSREKTEEVIAENPGKKLVPYYTVKEFVESLETPRRILLMVKAGAGTDAAIDSLKPYLDKGDIIIDGGNTFFQDTIRRNRELSAEGFNFIGTGVSGGEEGALKGPSIMPGGQKEAYELVAPILTKIAAVAEDGEPCVTYIGADGAGHYVKMVHNGIEYGDMQLIAEAYSLLKGGLNLTNEELAQTFTEWNNGELSSYLIDITKDIFTKKDEDGNYLVDVILDEAANKGTGKWTSQSALDLGEPLSLITESVFARYISSLKDQRVAASKVLSGPQAQPAGDKAEFIEKVRRALYLGKIVSYAQGFSQLRAASEEYNWDLNYGEIAKIFRAGCIIRAQFLQKITDAYAENPQIANLLLAPYFKQIADDYQQALRDVVAYAVQNGIPVPTFSAAVAYYDSYRAAVLPANLIQAQRDYFGAHTYKRIDKEGVFHTEWLD');""")


lab4.commit()

#### 1.2 Gene in Glycolysis / Gluconeogenesis pathway

##### 1.2.1 Homo Sapiens
1.2.1.1
https://www.genome.jp/dbget-bin/www_bget?hsa:5236+hsa:55276
https://www.ncbi.nlm.nih.gov/nuccore/NC_000001.11?report=genbank&from=63593411&to=63660245
1.2.1.2
https://www.genome.jp/dbget-bin/www_bget?hsa:226+hsa:229+hsa:230
https://www.ncbi.nlm.nih.gov/nuccore/NC_000016.10?report=genbank&from=30064279&to=30072207
1.2.1.3
https://www.genome.jp/dbget-bin/www_bget?hsa:2538
1.2.1.4
https://www.ncbi.nlm.nih.gov/nuccore/NC_000002.12?report=genbank&from=168901223&to=168910000
1.2.1.5
https://www.genome.jp/dbget-bin/www_bget?hsa:92579
1.2.1.6
https://www.genome.jp/dbget-bin/www_bget?hsa:2023+hsa:2026+hsa:2027+hsa:387712

In [36]:
lab = lab4.cursor()
lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(13,
                                'PGM1',
                                'phosphoglucomutase 1',
                                'Homo Sapiens',
                                'atggtgaagatcgtgacagttaagacccaggcgtaccaggaccagaagccgggcacgagcgggctgcggaagcgggtgaaggtgttccagagcagcgccaactacgcggagaacttcatccagagtatcatctccaccgtggagccggcgcagcggcaggaggccacgctggtggtgggcggggacggccggttctacatgaaggaggccatccagctcatcgctcgcatcgctgccgccaacgggatcggtcgcttggttatcggacagaatggaatcctctccacccctgctgtatcctgcatcattagaaaaatcaaagccattggtgggatcattctgacagccagtcacaacccagggggccccaatggagattttggaatcaaattcaatatttctaatggaggtcctgctccagaagcaataactgataaaattttccaaatcagcaagacaattgaagaatatgcagtttgccctgacctgaaagtagaccttggtgttctgggaaagcagcagtttgacttggaaaataagttcaaacccttcacagtggaaattgtggattcggtagaagcttatgctacaatgctgagaagcatctttgatttcagtgcactgaaagaactactttctgggccaaaccgactgaagatccgtattgatgctatgcatggagttgtgggaccgtatgtaaagaagatcctctgtgaagaactcggtgcccctgcgaactcggcagttaactgcgttcctctggaggactttggaggccaccaccctgaccccaacctcacctatgcagctgacctggtggagaccatgaagtcaggagagcatgattttggggctgcctttgatggagatggggatcgaaacatgattctgggcaagcatgggttctttgtgaacccttcagactctgtggctgtcattgctgccaacatcttcagcattccgtatttccagcagactggggtccgcggctttgcacggagcatgcccacgagtggtgctctggaccgggtggctagtgctacaaagattgctttgtatgagaccccaactggctggaagttttttgggaatttgatggacgcgagcaaactgtccctttgtggggaggagagcttcgggaccggttctgaccacatccgtgagaaagatggactgtgggctgtccttgcctggctctccatcctagccacccgcaagcagagtgtggaggacattctcaaagatcattggcaaaagtatggccggaatttcttcaccaggtatgattacgaggaggtggaagctgagggcgcaaacaaaatgatgaaggacttggaggccctgatgtttgatcgctcctttgtggggaagcagttctcagcaaatgacaaagtttacactgtggagaaggccgataactttgaatacagcgacccagtggatggaagcatttcaagaaatcagggcttgcgcctcattttcacagatggttctcgaatcgtcttccgactgagcggcactgggagtgccggggccaccattcggctgtacatcgatagctatgagaaggacgttgccaagattaaccaggacccccaggtcatgttggccccccttatttccattgctctgaaagtgtcccagctgcaggagaggacgggacgcactgcacccactgtcatcacctaa',
                                '1p31.3',
                                63593411,
                                63660245,
                                'MVKIVTVKTQAYQDQKPGTSGLRKRVKVFQSSANYAENFIQSIISTVEPAQRQEATLVVGGDGRFYMKEAIQLIARIAAANGIGRLVIGQNGILSTPAVSCIIRKIKAIGGIILTASHNPGGPNGDFGIKFNISNGGPAPEAITDKIFQISKTIEEYAVCPDLKVDLGVLGKQQFDLENKFKPFTVEIVDSVEAYATMLRSIFDFSALKELLSGPNRLKIRIDAMHGVVGPYVKKILCEELGAPANSAVNCVPLEDFGGHHPDPNLTYAADLVETMKSGEHDFGAAFDGDGDRNMILGKHGFFVNPSDSVAVIAANIFSIPYFQQTGVRGFARSMPTSGALDRVASATKIALYETPTGWKFFGNLMDASKLSLCGEESFGTGSDHIREKDGLWAVLAWLSILATRKQSVEDILKDHWQKYGRNFFTRYDYEEVEAEGANKMMKDLEALMFDRSFVGKQFSANDKVYTVEKADNFEYSDPVDGSISRNQGLRLIFTDGSRIVFRLSGTGSAGATIRLYIDSYEKDVAKINQDPQVMLAPLISIALKVSQLQERTGRTAPTVIT');""")


lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(14,
                                'ALDA',
                                'fructose-bisphosphate aldolase',
                                'Homo Sapiens',
                                'atgccctaccaatatccagcactgaccccggagcagaagaaggagctgtctgacatcgctcaccgcatcgtggcacctggcaagggcatcctggctgcagatgagtccactgggagcattgccaagcggctgcagtccattggcaccgagaacaccgaggagaaccggcgcttctaccgccagctgctgctgacagctgacgaccgcgtgaacccctgcattgggggtgtcatcctcttccatgagacactctaccagaaggcggatgatgggcgtcccttcccccaagttatcaaatccaagggcggtgttgtgggcatcaaggtagacaagggcgtggtccccctggcagggacaaatggcgagactaccacccaagggttggatgggctgtctgagcgctgtgcccagtacaagaaggacggagctgacttcgccaagtggcgttgtgtgctgaagattggggaacacaccccctcagccctcgccatcatggaaaatgccaatgttctggcccgttatgccagtatctgccagcagaatggcattgtgcccatcgtggagcctgagatcctccctgatggggaccatgacttgaagcgctgccagtatgtgaccgagaaggtgctggctgctgtctacaaggctctgagtgaccaccacatctacctggaaggcaccttgctgaagcccaacatggtcaccccaggccatgcttgcactcagaagttttctcatgaggagattgccatggcgaccgtcacagcgctgcgccgcacagtgccccccgctgtcactgggatcaccttcctgtctggaggccagagtgaggaggaggcgtccatcaacctcaatgccattaacaagtgccccctgctgaagccctgggccctgaccttctcctacggccgagccctgcaggcctctgccctgaaggcctggggcgggaagaaggagaacctgaaggctgcgcaggaggagtatgtcaagcgagccctggccaacagccttgcctgtcaaggaaagtacactccgagcggtcaggctggggctgctgccagcgagtccctcttcgtctctaaccacgcctattaa',
                                '16p11.2',
                                30064279,
                                30072207,
                                'MPYQYPALTPEQKKELSDIAHRIVAPGKGILAADESTGSIAKRLQSIGTENTEENRRFYRQLLLTADDRVNPCIGGVILFHETLYQKADDGRPFPQVIKSKGGVVGIKVDKGVVPLAGTNGETTTQGLDGLSERCAQYKKDGADFAKWRCVLKIGEHTPSALAIMENANVLARYASICQQNGIVPIVEPEILPDGDHDLKRCQYVTEKVLAAVYKALSDHHIYLEGTLLKPNMVTPGHACTQKFSHEEIAMATVTALRRTVPPAVTGITFLSGGQSEEEASINLNAINKCPLLKPWALTFSYGRALQASALKAWGGKKENLKAAQEEYVKRALANSLACQGKYTPSGQAGAAASESLFVSNHAY');""")


lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(15,
                                'G6PC',
                                'glucose-6-phosphatase catalytic subunit',
                                'Homo Sapiens',
                                'atggaggaaggaatgaatgttctccatgactttgggatccagtcaacacattacctccaggtgaattaccaagactcccaggactggttcatcttggtgtccgtgatcgcagacctcaggaatgccttctacgtcctcttccccatctggttccatcttcaggaagctgtgggcattaaactcctttgggtagctgtgattggagactggctcaacctcgtctttaagtggattctctttggacagcgtccatactggtgggttttggatactgactactacagcaacacttccgtgcccctgataaagcagttccctgtaacctgtgagactggaccagggagcccctctggccatgccatgggcacagcaggtgtatactacgtgatggtcacatctactctttccatctttcagggaaagataaagccgacctacagatttcggtgcttgaatgtcattttgtggttgggattctgggctgtgcagctgaatgtctgtctgtcacgaatctaccttgctgctcattttcctcatcaagttgttgctggagtcctgtcaggcattgctgttgcagaaactttcagccacatccacagcatctataatgccagcctcaagaaatattttctcattaccttcttcctgttcagcttcgccatcggattttatctgctgctcaagggactgggtgtagacctcctgtggactctggagaaagcccagaggtggtgcgagcagccagaatgggtccacattgacaccacaccctttgccagcctcctcaagaacctgggcacgctctttggcctggggctggctctcaactccagcatgtacagggagagctgcaaggggaaactcagcaagtggctcccattccgcctcagctctattgtagcctccctcgtcctcctgcacgtctttgactccttgaaacccccatcccaagtcgagctggtcttctacgtcttgtccttctgcaagagtgcggtagtgcccctggcatccgtcagtgtcatcccctactgcctcgcccaggtcctgggccagccgcacaagaagtcgttgtaa',
                                '17q21.31',
                                798586,
                                799581,
                                'MEEGMNVLHDFGIQSTHYLQVNYQDSQDWFILVSVIADLRNAFYVLFPIWFHLQEAVGIKLLWVAVIGDWLNLVFKWILFGQRPYWWVLDTDYYSNTSVPLIKQFPVTCETGPGSPSGHAMGTAGVYYVMVTSTLSIFQGKIKPTYRFRCLNVILWLGFWAVQLNVCLSRIYLAAHFPHQVVAGVLSGIAVAETFSHIHSIYNASLKKYFLITFFLFSFAIGFYLLLKGLGVDLLWTLEKAQRWCEQPEWVHIDTTPFASLLKNLGTLFGLGLALNSSMYRESCKGKLSKWLPFRLSSIVASLVLLHVFDSLKPPSQVELVFYVLSFCKSAVVPLASVSVIPYCLAQVLGQPHKKSL');""")

lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(16,
                                'G6PC1',
                                'glucose-6-phosphatase catalytic subunit',
                                'Homo Sapiens',
                                'atggatttccttcacaggaatggagtgctcataattcagcatttgcagaaggactaccgagcttactacacttttctaaattttatgtccaatgttggagaccccaggaatatctttttcatttattttccactttgttttcaatttaatcagacagttggaaccaagatgatatgggtagcagtcattggggattggttaaatcttatatttaaatggatattatttggtcatcgaccttactggtgggtccaagaaactcagatttacccaaatcactcaagtccatgccttgaacagttccctactacatgtgaaacaggtccaggaagtccatctggccatgcaatgggcgcatcctgtgtctggtatgtcatggtaaccgctgccctgagccacactgtctgtgggatggataagttctctatcactctgcacagactgacctggtcatttctttggagtgttttttggttgattcaaatcagtgtctgcatctccagagtattcatagcaacacattttcctcatcaagttattcttggagtaattggtggcatgctggtggcagaggcctttgaacacactccaggcatccaaacggccagtctgggcacatacctgaagaccaacctctttctcttcctgtttgcagttggcttttacctgcttcttagggtgctcaacattgacctgctgtggtccgtgcccatagccaaaaagtggtgtgctaaccccgactggatccacattgacaccacgccttttgctggactcgtgagaaaccttggggtcctctttggcttgggctttgcaatcaactcagagatgttcctcctgagctgccgagggggaaataactacacactgagcttccggttgctctgtgccttgacctcattgacaatactgcagctctaccatttcctccagatcccgactcacgaagagcatttattttatgtgctgtctttttgtaaaagtgcatccattcccctaactgtggttgctttcattccctactctgttcatatgttaatgaaacaaagcggaaagaagagtcagtag',
                                '2q31.1',
                                168901223,
                                168910000,
                                'MDFLHRNGVLIIQHLQKDYRAYYTFLNFMSNVGDPRNIFFIYFPLCFQFNQTVGTKMIWVAVIGDWLNLIFKWILFGHRPYWWVQETQIYPNHSSPCLEQFPTTCETGPGSPSGHAMGASCVWYVMVTAALSHTVCGMDKFSITLHRLTWSFLWSVFWLIQISVCISRVFIATHFPHQVILGVIGGMLVAEAFEHTPGIQTASLGTYLKTNLFLFLFAVGFYLLLRVLNIDLLWSVPIAKKWCANPDWIHIDTTPFAGLVRNLGVLFGLGFAINSEMFLLSCRGGNNYTLSFRLLCALTSLTILQLYHFLQIPTHEEHLFYVLSFCKSASIPLTVVAFIPYSVHMLMKQSGKKSQ');""")



lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(17,
                                'G6PC2',
                                'glucose-6-phosphatase catalytic subunit',
                                'Homo Sapiens',
                                'atggagtccacgctgggcgcgggcatcgtgatagccgaggcgctacagaaccagctagcctggctggagaacgtgtggctctggatcacctttctgggcgatcccaagatcctctttctgttctacttccccgcggcctactacgcctcccgccgtgtgggcatcgcggtgctctggatcagcctcatcaccgagtggctcaacctcatcttcaagtggtttctttttggagacaggcccttttggtgggtccatgagtctggttactacagccaggctccagcccaggttcaccagttcccctcttcttgtgagactggtccaggcagcccttctggacactgcatgatcacaggagcagccctctggcccataatgacggccctgtcttcgcaggtggccactcgggcccgcagccgctgggtaagggtgatgcctagcctggcttattgcaccttccttttggcggttggcttgtcgcgaatcttcatcttagcacatttccctcaccaggtgctggctggcctaataactggcgctgtcctgggctggctgatgactccccgagtgcctatggagcgggagctaagcttctatgggttgactgcactggccctcatgctaggcaccagcctcatctattggaccctctttacactgggcctggatctttcttggtccatcagcctagccttcaagtggtgtgagcggcctgagtggatacacgtggatagccggccctttgcctccctgagccgtgactcaggggctgccctgggcctgggcattgccttgcactctccctgctatgcccaggtgcgtcgggcacagctgggaaatggccagaagatagcctgccttgtgctggccatggggctgctgggccccctggactggctgggccacccccctcagatcagcctcttctacattttcaatttcctcaagtacaccctctggccatgcctagtcctggccctcgtgccctgggcagtgcacatgttcagtgcccaggaagcaccgcccatccactcttcctga',
                                '17q21.31',
                                44070700,
                                44076344,
                                'MESTLGAGIVIAEALQNQLAWLENVWLWITFLGDPKILFLFYFPAAYYASRRVGIAVLWISLITEWLNLIFKWFLFGDRPFWWVHESGYYSQAPAQVHQFPSSCETGPGSPSGHCMITGAALWPIMTALSSQVATRARSRWVRVMPSLAYCTFLLAVGLSRIFILAHFPHQVLAGLITGAVLGWLMTPRVPMERELSFYGLTALALMLGTSLIYWTLFTLGLDLSWSISLAFKWCERPEWIHVDSRPFASLSRDSGAALGLGIALHSPCYAQVRRAQLGNGQKIACLVLAMGLLGPLDWLGHPPQISLFYIFNFLKYTLWPCLVLALVPWAVHMFSAQEAPPIHSS');""")



lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(18,
                                'ENO1',
                                'enolase 1',
                                'Homo Sapiens',
                                'atgtctattctcaagatccatgccagggagatctttgactctcgcgggaatcccactgttgaggttgatctcttcacctcaaaaggtctcttcagagctgctgtgcccagtggtgcttcaactggtatctatgaggccctagagctccgggacaatgataagactcgctatatggggaagggtgtctcaaaggctgttgagcacatcaataaaactattgcgcctgccctggttagcaagaaactgaacgtcacagaacaagagaagattgacaaactgatgatcgagatggatggaacagaaaataaatctaagtttggtgcgaacgccattctgggggtgtcccttgccgtctgcaaagctggtgccgttgagaagggggtccccctgtaccgccacatcgctgacttggctggcaactctgaagtcatcctgccagtcccggcgttcaatgtcatcaatggcggttctcatgctggcaacaagctggccatgcaggagttcatgatcctcccagtcggtgcagcaaacttcagggaagccatgcgcattggagcagaggtttaccacaacctgaagaatgtcatcaaggagaaatatgggaaagatgccaccaatgtgggggatgaaggcgggtttgctcccaacatcctggagaataaagaaggcctggagctgctgaagactgctattgggaaagctggctacactgataaggtggtcatcggcatggacgtagcggcctccgagttcttcaggtctgggaagtatgacctggacttcaagtctcccgatgaccccagcaggtacatctcgcctgaccagctggctgacctgtacaagtccttcatcaaggactacccagtggtgtctatcgaagatccctttgaccaggatgactggggagcttggcagaagttcacagccagtgcaggaatccaggtagtgggggatgatctcacagtgaccaacccaaagaggatcgccaaggccgtgaacgagaagtcctgcaactgcctcctgctcaaagtcaaccagattggctccgtgaccgagtctcttcaggcgtgcaagctggcccaggccaatggttggggcgtcatggtgtctcatcgttcgggggagactgaagataccttcatcgctgacctggttgtggggctgtgcactgggcagatcaagactggtgccccttgccgatctgagcgcttggccaagtacaaccagctcctcagaattgaagaggagctgggcagcaaggctaagtttgccggcaggaacttcagaaaccccttggccaagtaa',
                                '1p36.23',
                                8861000,
                                8878686,
                                'MSILKIHAREIFDSRGNPTVEVDLFTSKGLFRAAVPSGASTGIYEALELRDNDKTRYMGKGVSKAVEHINKTIAPALVSKKLNVTEQEKIDKLMIEMDGTENKSKFGANAILGVSLAVCKAGAVEKGVPLYRHIADLAGNSEVILPVPAFNVINGGSHAGNKLAMQEFMILPVGAANFREAMRIGAEVYHNLKNVIKEKYGKDATNVGDEGGFAPNILENKEGLELLKTAIGKAGYTDKVVIGMDVAASEFFRSGKYDLDFKSPDDPSRYISPDQLADLYKSFIKDYPVVSIEDPFDQDDWGAWQKFTASAGIQVVGDDLTVTNPKRIAKAVNEKSCNCLLLKVNQIGSVTESLQACKLAQANGWGVMVSHRSGETEDTFIADLVVGLCTGQIKTGAPCRSERLAKYNQLLRIEEELGSKAKFAGRNFRNPLAK');""")




lab4.commit()

#### 1.2.2 Drosophila melanogaster
1.2.2.1
https://www.genome.jp/dbget-bin/www_bget?dme:Dmel_CG10202+dme:Dmel_CG5165+dme:Dmel_CG8073
https://www.ncbi.nlm.nih.gov/nuccore/NT_033778.4?report=genbank&from=14817857&to=14819987&strand=true
1.2.2.2
https://www.genome.jp/dbget-bin/www_bget?dme:Dmel_CG5432+dme:Dmel_CG6058
https://www.ncbi.nlm.nih.gov/nuccore/NT_033777.3?report=genbank&from=26414088&to=26416192
1.2.2.3
https://www.genome.jp/dbget-bin/www_bget?dme:Dmel_CG15400
https://www.ncbi.nlm.nih.gov/nuccore/NT_033779.5?report=genbank&from=2814336&to=2815760&strand=true
1.2.2.4
https://www.genome.jp/dbget-bin/www_bget?dme:Dmel_CG17654
https://www.ncbi.nlm.nih.gov/nuccore/NT_033779.5?report=genbank&from=1724768&to=1729636&strand=true

In [37]:
lab = lab4.cursor()
lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(19,
                                'Pgm2b',
                                'phosphoglucomutase',
                                'Drosophila melanogaster',
                                'atgtctatctcagtgaagcggaaaacggtgatttcaccgcaggaactcctgaagacactcgagctgtccggcgaagaggacctcgatctgcagatcaagaactgggtgatgtgggaccgcaacgaggcgacgctccagcaggtgactgaggcagtcagggatcaggattggaaggcgttgcgggtgagactgtgccataggatcacctatttgacaactggcttgaggggagtgatgcgcgcaggcttcgactctttgaacgatgtggtgatcatcgaagtggcccagggcatctgcgcctacctcgtcgatgcctatccaagcatccagaagaggcaaacacagggcgtggtcgttggctacgatggcaggtacaatagcaagcggtttgcccaactcatcgccaccgtgttcctgaacaacgacttcaaggtgttcctcttcactcggatgatcccgacaccctttatacccttcaccgtcgtcacgctccagtgcctggcggggatcgtggtcactgcctcccacaacgttaaggaggacaatggcatcaaggtatattggtcgaatggggctcaggcgatggcaccgcacgatcagcggattcatgactatatgatgaataacctagaaccaaagccttcgtcctgggaaacttcactggtacttgaccatcccttggtggaggatccctatcgtcagatatacccactcttttacgaggctctcaagacgcttattcccccaatttacctggaaactaatgagtgcagccagttgaggttcatctatacagctcttcacggtgtgggttatcccttcatgagggaggccttctaccaggcgcgactcaagccggttattcccgtcgtggaacagaaagaggccgatccagagtttcccaccctcgttaaaccaaatccggaagagggcaaggaagcgctgaagctggccataaagaaggcggatgcggaacactgcaccttggttctggccaatgatccggatgtggatcgcttggctgtggcagagctggatccgcgtggccgctggaagctgttcaatggcaacgaactgggtgccctgctcggctggtgggcactggagaactacaagactaggacacccaagccagcagtgaccaattgcataatgatagccacactggtcagctcacgcatcctggcggcaatggcgagagttgagggcttcatctttgtggagggcatgcccagtttcccctggatggcacatcgcgccttggagctggaaaagtctggaagaacagtactatttgcatttgaggagtgctttggctatatgttcggaatgagcctgccggataaggatggcattggagctgccatgcagttggccagcatggcctgttatctgcgcagcactagaaatgtgacgctgatcgagaagctaagggagatctacgatacgtatggctaccattcgtcgatctcgtcggtttatatggccgatagtccagagacaatcactagcgtcttcgatcatttgcgcaactttacggacgaagagggatatccgaagttcattctggatgaagaattcgaagtggttcatatccgggatttgaccatcggactggacacttccttcagcgatggaaaggctcgtatgccggtcactccagatgcccagctaattacgtttaccttcaccaatggctatgtggttaccctgcgatcggcacccaacgatattaagatcaaacttaatgcggagatctgtggcttgccggaggaaaagcagtgggaggagctacacgataaactgaacaggatgaccaatgccgtggtggaggagtttcttcaaccagaggagaatggtcttacggatgcctcaacaattcaataa',
                                '2R',
                                14817857,
                                14819987,
                                'MSISVKRKTVISPQELLKTLELSGEEDLDLQIKNWVMWDRNEATLQQVTEAVRDQDWKALRVRLCHRITYLTTGLRGVMRAGFDSLNDVVIIEVAQGICAYLVDAYPSIQKRQTQGVVVGYDGRYNSKRFAQLIATVFLNNDFKVFLFTRMIPTPFIPFTVVTLQCLAGIVVTASHNVKEDNGIKVYWSNGAQAMAPHDQRIHDYMMNNLEPKPSSWETSLVLDHPLVEDPYRQIYPLFYEALKTLIPPIYLETNECSQLRFIYTALHGVGYPFMREAFYQARLKPVIPVVEQKEADPEFPTLVKPNPEEGKEALKLAIKKADAEHCTLVLANDPDVDRLAVAELDPRGRWKLFNGNELGALLGWWALENYKTRTPKPAVTNCIMIATLVSSRILAAMARVEGFIFVEGMPSFPWMAHRALELEKSGRTVLFAFEECFGYMFGMSLPDKDGIGAAMQLASMACYLRSTRNVTLIEKLREIYDTYGYHSSISSVYMADSPETITSVFDHLRNFTDEEGYPKFILDEEFEVVHIRDLTIGLDTSFSDGKARMPVTPDAQLITFTFTNGYVVTLRSAPNDIKIKLNAEICGLPEEKQWEELHDKLNRMTNAVVEEFLQPEENGLTDASTIQ');""")


lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(20,
                                'Ald2',
                                'fructose-bisphosphate aldolase',
                                'Drosophila melanogaster',
                                'atgactacgcatttctactacccgaacaaggagctgcaggaagaactcatctgcatatcgaaggcgttggtggctcctggtaagggaatcctggcggccgacgagtccagtgcagtgatgggcaagcgatttcagttgatcggtgtggagaacacggaggagaatcgccggctataccgccaaatgctattcacgaccgatccgaagatagcggagaatatatccggcgtgatattctaccatgaaacactgcatcagcgtacggatgacggactgccattcgtagaggccctcagaaagaagggcatcctgacgggaataaaggtagacaagcacttttcaccactcttcggctccgaggatgagttcaccacccagggtctggatgatctagccaatcgatgtgcacagtacaagaaggagggctgcagctttgccaagtggaggtgcatcctgaagatcactaagaatactccttcgccgcaggccattttggaaaacgctaatgtcatggcccggtatgcagccatctgtcaatcgcagcgactagtacccatcattagtcccgaggtcctggccaccggagatcatgacttggatcggtgtcagaaggtcaacgaaattctcctggctggagtatacaaggctcttagtgatcaccacgtttttctcgagggaactcttttgcaacccagcatggtgatgcctggattgcagagcaacaaaaatcatccgccagcggatattggagtggctacagttctcgccattaggcgaagtgttcctccggccgtaatgggagtacttttttgtggtggcgctcaatcagaagaggaggccacggtccatttgaatgcaattaacaatgttccgctttgtaagccttgggccatgacctttgcctttgatcgggctcttcaaacatcgattttgcgaacttggggtggcaagaaggagcagattagccatgctcaaaatgaacttatcaagcggtgcagggccaatggtcttgcaagcattggaaaatatgtaattggctctgtggaaagttcagcggccactgaaagactcattcaagaagccgtcgaattctaa',
                                '3R',
                                26414088,
                                26416192,
                                'MTTHFYYPNKELQEELICISKALVAPGKGILAADESSAVMGKRFQLIGVENTEENRRLYRQMLFTTDPKIAENISGVIFYHETLHQRTDDGLPFVEALRKKGILTGIKVDKHFSPLFGSEDEFTTQGLDDLANRCAQYKKEGCSFAKWRCILKITKNTPSPQAILENANVMARYAAICQSQRLVPIISPEVLATGDHDLDRCQKVNEILLAGVYKALSDHHVFLEGTLLQPSMVMPGLQSNKNHPPADIGVATVLAIRRSVPPAVMGVLFCGGAQSEEEATVHLNAINNVPLCKPWAMTFAFDRALQTSILRTWGGKKEQISHAQNELIKRCRANGLASIGKYVIGSVESSAATERLIQEAVEF');""")


lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(21,
                                'G6P',
                                'Glucose-6-Phosphatase',
                                'Drosophila melanogaster',
                                'atggagtcgatagtgcacattctttcggatgcgtaccatacaacgctcacgcgggagcttttcatcaacgaatgggctcaggaacgcttgagttttggaaggcccctttggcattttctcagcgttcatttggagccaaacaaaatgttcaacatcattatccccctatgtggtatcttcagtcaggaaatcctcgtgcatctcttcacggcatttaccctgattagcacactgaactccttcgaaaaatggatatatccggagacgcgtcctttgtggtttctgcgagagcagtttgccaataatgtggttgtaaagaaaccggcggtggccttggaaagtcatcagctgagctgcgagatgaccggtgggctgccctgcgcccactcaatgaccttcacggtgttcgtactcatcctggcctcgttcttcttcgttcactgctgggatcgctttgctgcgttgcgctcttccttctgccgctgcataatgtacctgctgatcattggaatggtggtctgtatgtggctgagtcgcctctacctggccaccgagtttctgcaccagtgcatactgggaagttacctgggaattaggtctctttgcacctttgagggaaatgtgaagtacttgttctcgcgaccacgtcgctatgcggtctcagctgttttcttcttgggaggattggcattgtcagtgtactatgtgaagctggaactgaatatcgatccccattggtcggtgcgagaggcatttaaatggtgtccagaacccacatatttgcgtcatgaagttggtccaatctttgcacttgtcagagatctgggaaatctaatgggattggctttggcctcgccactatataagctggaaatgaaacaatcatcattttggcggcgatgccgattccttggagttctggagtttgtcaactatggattgcgcttttccacgtttaagcagtctggtcgcttcgttttcttgacctatgagttcttaagaaatgtcattcattccctagtactgattaagtacgtatcgaaattttactag',
                                '2L',
                                2814336,
                                2815760,
                                'MESIVHILSDAYHTTLTRELFINEWAQERLSFGRPLWHFLSVHLEPNKMFNIIIPLCGIFSQEILVHLFTAFTLISTLNSFEKWIYPETRPLWFLREQFANNVVVKKPAVALESHQLSCEMTGGLPCAHSMTFTVFVLILASFFFVHCWDRFAALRSSFCRCIMYLLIIGMVVCMWLSRLYLATEFLHQCILGSYLGIRSLCTFEGNVKYLFSRPRRYAVSAVFFLGGLALSVYYVKLELNIDPHWSVREAFKWCPEPTYLRHEVGPIFALVRDLGNLMGLALASPLYKLEMKQSSFWRRCRFLGVLEFVNYGLRFSTFKQSGRFVFLTYEFLRNVIHSLVLIKYVSKFY');""")


lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(22,
                                'Eno',
                                'enolase',
                                'Drosophila melanogaster',
                                'atgtcttggaccgcttcagttttcttgaggacttccaccactagcatgaagtttctgcgtctgcgctggcctctccccagaattccccagaataaatcggcaaacgttgcgccgcgtttcagaagcaaatcagcagtcagccagctctcatctggatttaaatttgtgcagatccgcaaaagtacttgtgacagcaacgagatgaccatcaaagcgatcaaggcccgtcaaatctacgactcccgtggcaaccccaccgtggaggtcgacctgaccaccgagctgggactcttccgagccgccgtgccctccggcgcctccactggcgtccacgaggccctggagctgcgcgacaacgacaaggccaactaccatggcaagtcggtgctgaaggccgtgggccatgtgaacgacaccctgggacccgagctgatcaaggccaatctggatgtggttgaccaggcgtccattgacaacttcatgatcaagttggacggcaccgagaacaagagcaagttcggagccaacgccatcctgggcgtttccctggccgtggccaaggctggagccgccaagaagggcgtgccgctgtacaaacacattgccgatctggctggcaacaaggagatcatcctgccggtgcccgctttcaacgtgatcaacggcggcagccacgccggcaacaagctggccatgcaggagttcatgatcctgcccaccggcgccaccagcttcacagaggccatgaagatgggctccgaggtgtaccaccacctgaagaatgtgatcaaggccaagttcggtctggacgccaccgctgtgggcgatgagggcggcttcgcccccaacatccagtccaacaaggaggctctgaacctgatcagcgatgccatcgccaaggccggatacaccggcaagatcgagatcggcatggacgtggccgcctccgagttctacaaggatggccagtacgatctggacttcaagaacgagaagagcgacaagtcgcagtggctgcccgccgacaagctggccaacctgtaccaggagtttattaaggacttccccatcgtctcgattgaggatccctttgaccaggaccactgggaggcctggtccaacctgaccggctgcaccgacatccagatcgtgggcgatgatctgaccgtgaccaaccccaagcgtattgccaccgccgtggagaagaaggcctgcaactgcctgctcctgaaggtcaaccagatcggcaccgtcaccgagtccattgccgcccatctgctggccaagaagaacggctggggcaccatggtctcccaccgttccggtgagaccgaggactcgttcatcggtgacctggtcgtcggtctgtccaccggccagatcaagaccggagctccatgccgctcggagcgtctggccaagtacaaccagatcctgcgcatcgaggaggagatcggcgctggcgtcaagttcgccggcaagtcgttcaggaagccgcagtaa',
                                '2L',
                                1724768,
                                1729636,
                                'MSWTASVFLRTSTTSMKFLRLRWPLPRIPQNKSANVAPRFRSKSAVSQLSSGFKFVQIRKSTCDSNEMTIKAIKARQIYDSRGNPTVEVDLTTELGLFRAAVPSGASTGVHEALELRDNDKANYHGKSVLKAVGHVNDTLGPELIKANLDVVDQASIDNFMIKLDGTENKSKFGANAILGVSLAVAKAGAAKKGVPLYKHIADLAGNKEIILPVPAFNVINGGSHAGNKLAMQEFMILPTGATSFTEAMKMGSEVYHHLKNVIKAKFGLDATAVGDEGGFAPNIQSNKEALNLISDAIAKAGYTGKIEIGMDVAASEFYKDGQYDLDFKNEKSDKSQWLPADKLANLYQEFIKDFPIVSIEDPFDQDHWEAWSNLTGCTDIQIVGDDLTVTNPKRIATAVEKKACNCLLLKVNQIGTVTESIAAHLLAKKNGWGTMVSHRSGETEDSFIGDLVVGLSTGQIKTGAPCRSERLAKYNQILRIEEEIGAGVKFAGKSFRKPQ');""")


lab4.commit()

#### 1.2.3 Escherichia coli
1.2.3.1
https://www.genome.jp/dbget-bin/www_bget?eco:b1852
https://www.ncbi.nlm.nih.gov/gene/946370
https://www.ncbi.nlm.nih.gov/nuccore/NC_000913.3?report=genbank&from=1934839&to=1936314&strand=true
1.2.3.2
https://www.genome.jp/dbget-bin/www_bget?eco:b2097+eco:b2925
1.2.3.3
https://www.genome.jp/dbget-bin/www_bget?eco:b0767

In [38]:
lab = lab4.cursor()
lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(23,
                                'pgm',
                                'phosphoglucomutase',
                                'Escherichia coli',
                                'atggcaatccacaatcgtgcaggccaacctgcacaacagagtgatttgattaacgtcgcccaactgacggcgcaatattatgtactgaaaccagaagcagggaatgcggagcacgcggtgaaattcggtacttccggtcaccgtggcagtgcagcgcgccacagctttaacgagccgcacattctggcgatcgctcaggcaattgctgaagaacgtgcgaaaaacggcatcactggcccttgctatgtgggtaaagatactcacgccctgtccgaacctgcattcatttccgttctggaagtgctggcagcgaacggcgttgatgtcattgtgcaggaaaacaatggcttcaccccgacgcctgccgtttccaatgccatcctggttcacaataaaaaaggtggcccgctggcagacggtatcgtgattacaccgtcccataacccgccggaagatggtggaatcaaatacaatccgccaaatggtggcccggctgataccaacgtcactaaagtggtggaagacagggccaacgcactgctggccgatggcctgaaaggcgtgaagcgtatctccctcgacgaagcgatggcatccggtcatgtgaaagagcaggatctggtgcagccgttcgtggaaggtctggccgatatcgttgatatggccgcgattcagaaagcgggcctgacgctgggcgttgatccgctgggcggttccggtatcgaatactggaagcgtattggcgagtattacaacctcaacctgactatcgttaacgatcaggtcgatcaaaccttccgctttatgcaccttgataaagacggcgcgatccgtatggactgctcctccgagtgtgcgatggcgggcctgctggcactgcgtgataagttcgatctggcgtttgctaacgacccggattatgaccgtcacggtatcgtcactccggcaggtttgatgaatccgaaccactacctggcggtggcaatcaattacctgttccagcatcgtccgcagtggggcaaagatgttgccgtcggtaaaacgctggtttcatctgcgatgatcgaccgtgtggtcaacgacttgggccgtaaactggtagaagtcccggtaggtttcaaatggtttgtcgatggtctgttcgacggcagcttcggctttggcggcgaagagagtgcaggggcttccttcctgcgtttcgacggcacgccgtggtccaccgacaaagacggcatcatcatgtgtctgctggcggcggaaatcaccgctgtcaccggtaagaacccgcaggaacactacaacgaactggcaaaacgctttggtgcgccgagctacaaccgtttgcaggcagctgcgacttccgcacaaaaagcggcgctgtctaagctgtctccggaaatggtgagcgccagcaccctggcaggtgacccgatcaccgcgcgcctgactgctgctccgggcaacggtgcttctattggcggtctgaaagtgatgactgacaacggctggttcgccgcgcgtccgtcaggcacggaagacgcatataagatctactgcgaaagcttcctcggtgaagaacatcgcaagcagattgagaaagaagcggttgagattgttagcgaagttctgaaaaacgcgtaa',
                                'circular',
                                713558,
                                715198,
                                'MAIHNRAGQPAQQSDLINVAQLTAQYYVLKPEAGNAEHAVKFGTSGHRGSAARHSFNEPHILAIAQAIAEERAKNGITGPCYVGKDTHALSEPAFISVLEVLAANGVDVIVQENNGFTPTPAVSNAILVHNKKGGPLADGIVITPSHNPPEDGGIKYNPPNGGPADTNVTKVVEDRANALLADGLKGVKRISLDEAMASGHVKEQDLVQPFVEGLADIVDMAAIQKAGLTLGVDPLGGSGIEYWKRIGEYYNLNLTIVNDQVDQTFRFMHLDKDGAIRMDCSSECAMAGLLALRDKFDLAFANDPDYDRHGIVTPAGLMNPNHYLAVAINYLFQHRPQWGKDVAVGKTLVSSAMIDRVVNDLGRKLVEVPVGFKWFVDGLFDGSFGFGGEESAGASFLRFDGTPWSTDKDGIIMCLLAAEITAVTGKNPQEHYNELAKRFGAPSYNRLQAAATSAQKAALSKLSPEMVSASTLAGDPITARLTAAPGNGASIGGLKVMTDNGWFAARPSGTEDAYKIYCESFLGEEHRKQIEKEAVEIVSEVLKNA');""")


lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(24,
                                'fbaB',
                                'fructose-bisphosphate aldolase',
                                'Escherichia coli',
                                'atgacagatattgcgcagttgcttggcaaagacgccgacaaccttttacagcaccgttgtatgacaattccttctgaccagctttatctccccggacatgactacgtagaccgcgtaatgattgacaataatcgcccgccagcggtgttacgtaatatgcagacgttgtacaacaccgggcgtctggctggcacaggatatctttctattctgccggttgaccagggcgttgagcactctgccggagcttcatttgctgctaacccgctctactttgacccgaaaaacattgttgaactggcgatcgaagcgggctgtaactgtgtggcgtcaacttacggcgtgctggcgtcggtatcgcggcgttatgcgcatcgcattccattcctcgtcaaacttaatcacaacgagacgctaagttacccgaatacctacgatcaaacgctgtatgccagcgtggagcaggcgttcaacatgggcgcggttgcggttggtgcgactatctattttggctcggaagagtcacgtcgccagattgaagaaatttctgcggcttttgaacgtgcgcacgagctgggtatggtgacagtgctgtgggcctatttgcgtaactccgcctttaagaaagatggcgttgattaccatgtttccgccgacctgaccggtcaggcaaaccatctggcggcaaccatcggtgcagatatcgtcaaacaaaaaatggcggaaaataacggcggctataaagcaattaattacggttacaccgacgatcgtgtttacagcaaattgaccagcgaaaacccgattgatctggtgcgttatcagttagctaactgctatatgggtcgggctgggttgataaactccggcggtgctgcgggcggtgaaactgacctcagcgatgcagtgcgtactgcggttatcaacaaacgcgcaggcggaatggggctgattcttggacgtaaagcgttcaagaaatcgatggctgacggcgtgaaactgattaacgccgtgcaggacgtttatctcgatagcaaaattactatcgcctga',
                                'circular',
                                2177512,
                                2178564,
                                'MTDIAQLLGKDADNLLQHRCMTIPSDQLYLPGHDYVDRVMIDNNRPPAVLRNMQTLYNTGRLAGTGYLSILPVDQGVEHSAGASFAANPLYFDPKNIVELAIEAGCNCVASTYGVLASVSRRYAHRIPFLVKLNHNETLSYPNTYDQTLYASVEQAFNMGAVAVGATIYFGSEESRRQIEEISAAFERAHELGMVTVLWAYLRNSAFKKDGVDYHVSADLTGQANHLAATIGADIVKQKMAENNGGYKAINYGYTDDRVYSKLTSENPIDLVRYQLANCYMGRAGLINSGGAAGGETDLSDAVRTAVINKRAGGMGLILGRKAFKKSMADGVKLINAVQDVYLDSKITIA');""")

lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(25,
                                'eno',
                                'enolase',
                                'Escherichia coli',
                                'atgtccaaaatcgtaaaaatcatcggtcgtgaaatcatcgactcccgtggtaacccgactgttgaagccgaagtacatctggagggtggtttcgtcggtatggcagctgctccgtcaggtgcttctactggttcccgtgaagctctggaactgcgcgatggcgacaaatcccgtttcctgggtaaaggcgtaaccaaagctgttgctgcggtaaacggcccgatcgctcaggcgctgattggcaaagatgctaaagatcaggctggcattgacaagatcatgatcgacctggacggcaccgaaaacaaatccaaattcggcgcgaacgcaatcctggctgtatctctggctaacgccaaagctgctgcagctgctaaaggtatgccgctgtacgagcacatcgctgaactgaacggtactccgggcaaatactctatgccggttccgatgatgaacatcatcaacggtggtgagcacgctgacaacaacgttgatatccaggaattcatgattcagccggttggcgcgaaaactgtgaaagaagccatccgcatgggttctgaagttttccatcacctggcaaaagttctgaaagcgaaaggcatgaacactgctgttggtgacgaaggtggctatgcgccgaacctgggttccaacgctgaagctctggctgttatcgctgaagctgttaaagctgctggttatgaactgggcaaagacatcactttggcgatggactgcgcagcttctgaattctacaaagatggtaaatacgttctggctggcgaaggcaacaaagcgttcacctctgaagaattcactcacttcctggaagaactgaccaaacagtacccgatcgtttctatcgaagacggtctggacgaatctgactgggacggtttcgcataccagaccaaagttctgggcgacaaaatccagctggttggtgacgacctgttcgtaaccaacaccaagatcctgaaagaaggtatcgaaaaaggtatcgctaactccatcctgatcaaattcaaccagatcggttctctgaccgaaactctggctgcaatcaagatggcgaaagatgctggctacactgcagttatctctcaccgttctggcgaaactgaagacgctaccatcgctgacctggctgttggtactgctgcaggccagatcaaaactggttctatgagccgttctgaccgtgttgctaaatacaaccagctgattcgtatcgaagaagctctgggcgaaaaagcaccgtacaacggtcgtaaagagatcaaaggccaggcataa',
                                'circular',
                                2906643,
                                2907941,
                                'MSKIVKIIGREIIDSRGNPTVEAEVHLEGGFVGMAAAPSGASTGSREALELRDGDKSRFLGKGVTKAVAAVNGPIAQALIGKDAKDQAGIDKIMIDLDGTENKSKFGANAILAVSLANAKAAAAAKGMPLYEHIAELNGTPGKYSMPVPMMNIINGGEHADNNVDIQEFMIQPVGAKTVKEAIRMGSEVFHHLAKVLKAKGMNTAVGDEGGYAPNLGSNAEALAVIAEAVKAAGYELGKDITLAMDCAASEFYKDGKYVLAGEGNKAFTSEEFTHFLEELTKQYPIVSIEDGLDESDWDGFAYQTKVLGDKIQLVGDDLFVTNTKILKEGIEKGIANSILIKFNQIGSLTETLAAIKMAKDAGYTAVISHRSGETEDATIADLAVGTAAGQIKTGSMSRSDRVAKYNQLIRIEEALGEKAPYNGRKEIKGQA');""")

lab4.commit()

#### 1.3 Citrate cycle (TCA cycle)

##### 1.3.1 Homo Sapiens
1.3.1.1
https://www.genome.jp/dbget-bin/www_bget?hsa:1431
https://www.ncbi.nlm.nih.gov/nuccore/NC_000001.11?report=genbank&from=63593411&to=63660245
1.3.1.2
https://www.genome.jp/dbget-bin/www_bget?hsa:4967+hsa:55753
https://www.ncbi.nlm.nih.gov/nuccore/NC_000007.14?report=genbank&from=44606572&to=44709066
1.3.1.3
https://www.genome.jp/dbget-bin/www_bget?hsa:2538
1.3.1.4
https://www.genome.jp/dbget-bin/www_bget?hsa:1743
https://www.ncbi.nlm.nih.gov/nuccore/NC_000014.9?report=genbank&from=74881913&to=74903743
1.3.1.5
https://www.genome.jp/dbget-bin/www_bget?hsa:8801+hsa:8802+hsa:8803
https://www.ncbi.nlm.nih.gov/nuccore/NC_000003.12?report=genbank&from=67360460&to=67654614&strand=true

In [39]:
lab = lab4.cursor()
lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(26,
                                'CS',
                                'citrate synthase',
                                'Homo Sapiens',
                                'atggctttacttactgcggccgcccggctcttgggaaccaagaatgcatcttgtcttgttcttgcagcccggcatgccagtgcttcctccacgaatttgaaagacatattggctgacctgatacctaaggagcaggccagaattaagactttcaggcagcaacatggcaagacggtggtgggccaaatcactgtggacatgatgtatggtggcatgagaggcatgaagggattggtctatgaaacatcagttcttgatcctgatgagggcatccgtttccgaggctttagtatccctgaatgccagaaactgctacccaaggctaagggtggggaagaacccctgcctgagggcttattttggctgctggtaactggacatatcccaacagaggaacaggtatcttggctctcaaaagagtgggcaaagagggcagctctgccttcccatgtggtcaccatgctggacaactttcccaccaatctacaccccatgtctcagctcagtgcagctgttacagccctcaacagtgaaagtaactttgcccgagcatatgcacagggtatcagccgaaccaagtactgggagttgatttatgaagactctatggatctaatcgcaaagctaccttgtgttgcagcaaagatctaccgaaatctctacagagaaggcagcggtattggggccattgactctaacctggactggtctcacaatttcaccaacatgttaggctatactgatcatcagttcactgagctcacgcgcctgtacctcaccatccacagtgaccatgagggtggcaatgtaagtgcccataccagccatttggtgggcagtgccctttccgacccttacctgtcctttgcagcagccatgaacgggctggcagggcctctccatggactggcaaatcaggaagtgcttgtctggctaacacagctgcagaaggaagttggcaaagatgtgtcagatgagaagttacgagactacatctggaacacactcaactcaggacgggttgttccaggctatggccatgcagtactaaggaagactgatccgcgatatacctgtcagcgagagtttgctctgaaacacctgcctaatgaccccatgtttaagttggttgctcagctgtacaagattgtgcccaatgtcctcttagagcagggtaaagccaagaatccttggcccaatgtagatgctcacagtggggtgctgctccagtattatggcatgacggagatgaattactacacggtcctgtttggggtgtcacgagcattgggtgtactggcacagctcatctggagccgagccttaggcttccctctagaaaggcccaagtccatgagcacagagggtctgatgaagtttgtggactctaagtcagggtaa',
                                '12q13.3',
                                56271699,
                                56300330,
                                'MALLTAAARLLGTKNASCLVLAARHASASSTNLKDILADLIPKEQARIKTFRQQHGKTVVGQITVDMMYGGMRGMKGLVYETSVLDPDEGIRFRGFSIPECQKLLPKAKGGEEPLPEGLFWLLVTGHIPTEEQVSWLSKEWAKRAALPSHVVTMLDNFPTNLHPMSQLSAAVTALNSESNFARAYAQGISRTKYWELIYEDSMDLIAKLPCVAAKIYRNLYREGSGIGAIDSNLDWSHNFTNMLGYTDHQFTELTRLYLTIHSDHEGGNVSAHTSHLVGSALSDPYLSFAAAMNGLAGPLHGLANQEVLVWLTQLQKEVGKDVSDEKLRDYIWNTLNSGRVVPGYGHAVLRKTDPRYTCQREFALKHLPNDPMFKLVAQLYKIVPNVLLEQGKAKNPWPNVDAHSGVLLQYYGMTEMNYYTVLFGVSRALGVLAQLIWSRALGFPLERPKSMSTEGLMKFVDSKSG');""")



lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(27,
                                'OGDH',
                                'oxoglutarate dehydrogenase',
                                'Homo Sapiens',
                                'atgtttcatttaaggacttgtgctgctaagttgaggccattgacggcttcccagactgttaagacattttcacaaaacagaccagcagcagctaggacatttcaacagattcggtgctattctgcacctgttgctgctgagccctttctcagtgggactagttcgaactatgtggaggagatgtactgtgcttggctggaaaaccccaaaagtgtacataagtcatgggacattttttttcgcaacacgaatgccggagccccaccgggcactgcctaccagagtccccttcccctgagccgaggctccctggctgctgtggcccatgcacagtccctggtagaagcacagcccaacgtggacaagctcgtggaggaccacctggcagtgcagtcgctcatcagggcatatcagatacgagggcaccatgtagcacagctggaccccctggggattttggatgctgatctggactcctccgtgcccgctgacattatctcatccacagacaaacttgggttctatggcctggatgagtctgacctcgacaaggtcttccacttgcccaccaccactttcatcgggggacaggaatcagcacttcctctgcgggagatcatccgtcggctggagatggcctactgccagcatattggggtggagttcatgttcatcaatgacctggagcagtgccagtggatccggcagaagtttgagacccctgggatcatgcagttcacaaatgaggagaaacggaccctgctggccaggcttgtgcggtccaccaggtttgaggagttcctacagcggaagtggtcctctgagaagcgctttggtctagaaggctgcgaggtactgatccctgccctcaagaccatcattgacaagtctagtgagaatggcgtggactacgtgatcatgggcatgccacacagagggcggctgaacgtgcttgcaaatgtcatcaggaaggagctggaacagatcttctgtcaattcgattcaaagctggaggcagctgatgagggctccggagatgtgaagtaccacctgggcatgtatcaccgcaggatcaatcgtgtcaccgacaggaacattaccttgtccttggtggccaacccttcccaccttgaggccgctgaccccgtggtgatgggcaagaccaaagccgaacagttttactgtggcgacactgaagggaaaaaggtcatgtccatcctgttgcatggggatgctgcatttgctggccagggcattgtgtacgagaccttccacctcagcgacctgccatcctacacaactcatggcaccgtgcacgtggtcgtcaacaaccagatcggcttcaccaccgaccctcggatggcccgctcctccccctaccccactgacgtggcccgagtggtgaatgcccccattttccacgtgaactcagatgaccccgaggctgtcatgtacgtgtgcaaagtggcggccgagtggaggagcaccttccacaaggacgtggttgtcgatttggtgtgttaccggcgcaacggccacaacgagatggatgagcccatgttcacgcagccgctcatgtacaagcagatccgcaagcagaagcctgtgttacagaagtacgctgagctgctggtgtcgcagggtgtggtcaaccagcctgagtatgaggaggaaatttccaagtatgataagatctgtgaggaagcttttgccagatctaaagatgagaagatcttgcacattaagcactggctggactctccctggcctggcttcttcaccctggacgggcagcccaggagcatgtcctgcccctccacgggtctgacggaggatattctgacacacatcgggaatgtggctagttctgtgcctgtggaaaactttactattcatggagggctgagccggatcttgaagactcgtggggaaatggtgaagaaccggactgtggactgggctctagcggagtacatggcgtttggctcgctcctgaaggagggcatccacattcggctgagcggccaggacgtggagcggggcacattcagccaccgccaccatgtgctccatgaccagaatgtggacaagagaacctgcatccccatgaaccatctctggcccaatcaggccccctatactgtgtgcaacagctcactgtctgagtacggcgtgctgggctttgagctgggcttcgccatggccagtcctaatgccctggtcctctgggaagcccaatttggtgacttccacaacacggcccagtgtatcatcgaccagttcatctgcccgggacaagccaagtgggtgcggcagaatggcatcgtgttgctgctgccccatggcatggagggcatgggtccagaacattcctccgcccgcccagagcggttcttgcagatgtgcaacgatgacccagatgtcctgccagaccttaaagaagccaacttcgacatcaatcagctatatgactgcaattgggttgttgtcaactgctccactcctggcaacttcttccacgtgctacgacgccagatcctgctgccattccggaagccgttaattatcttcacccccaaatccctgttgcgccaccccgaggccagatccagctttgatgagatgcttccaggaacccacttccagcgggtgatcccagaagatggccctgcagctcagaacccagaaaatgtcaaaaggcttctcttctgcaccggcaaagtgtattatgacctcacccgggagcgcaaagcacgcgacatggtggggcaggtggccatcacaaggattgagcagctgtcgccattcccctttgacctcctgctgaaggaggtgcagaagtaccccaatgctgagctggcctggtgccaggaggagcacaagaaccaaggctactatgactacgtgaagccaagacttcggaccaccatcagccgcgccaagcccgtctggtatgccggccgggacccagcggctgctccagccaccggcaacaagaagacccacctgacggagctgcagcgcctcctggacacggccttcgacctggacgtcttcaagaacttctcgtag',
                                '7p13',
                                44606572,
                                44709066,
                                'MFHLRTCAAKLRPLTASQTVKTFSQNRPAAARTFQQIRCYSAPVAAEPFLSGTSSNYVEEMYCAWLENPKSVHKSWDIFFRNTNAGAPPGTAYQSPLPLSRGSLAAVAHAQSLVEAQPNVDKLVEDHLAVQSLIRAYQIRGHHVAQLDPLGILDADLDSSVPADIISSTDKLGFYGLDESDLDKVFHLPTTTFIGGQESALPLREIIRRLEMAYCQHIGVEFMFINDLEQCQWIRQKFETPGIMQFTNEEKRTLLARLVRSTRFEEFLQRKWSSEKRFGLEGCEVLIPALKTIIDKSSENGVDYVIMGMPHRGRLNVLANVIRKELEQIFCQFDSKLEAADEGSGDVKYHLGMYHRRINRVTDRNITLSLVANPSHLEAADPVVMGKTKAEQFYCGDTEGKKVMSILLHGDAAFAGQGIVYETFHLSDLPSYTTHGTVHVVVNNQIGFTTDPRMARSSPYPTDVARVVNAPIFHVNSDDPEAVMYVCKVAAEWRSTFHKDVVVDLVCYRRNGHNEMDEPMFTQPLMYKQIRKQKPVLQKYAELLVSQGVVNQPEYEEEISKYDKICEEAFARSKDEKILHIKHWLDSPWPGFFTLDGQPRSMSCPSTGLTEDILTHIGNVASSVPVENFTIHGGLSRILKTRGEMVKNRTVDWALAEYMAFGSLLKEGIHIRLSGQDVERGTFSHRHHVLHDQNVDKRTCIPMNHLWPNQAPYTVCNSSLSEYGVLGFELGFAMASPNALVLWEAQFGDFHNTAQCIIDQFICPGQAKWVRQNGIVLLLPHGMEGMGPEHSSARPERFLQMCNDDPDVLPDLKEANFDINQLYDCNWVVVNCSTPGNFFHVLRRQILLPFRKPLIIFTPKSLLRHPEARSSFDEMLPGTHFQRVIPEDGPAAQNPENVKRLLFCTGKVYYDLTRERKARDMVGQVAITRIEQLSPFPFDLLLKEVQKYPNAELAWCQEEHKNQGYYDYVKPRLRTTISRAKPVWYAGRDPAAAPATGNKKTHLTELQRLLDTAFDLDVFKNFS');""")


lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(28,
                                'G6PC',
                                'glucose-6-phosphatase catalytic subunit',
                                'Homo Sapiens',
                                'atggaggaaggaatgaatgttctccatgactttgggatccagtcaacacattacctccaggtgaattaccaagactcccaggactggttcatcttggtgtccgtgatcgcagacctcaggaatgccttctacgtcctcttccccatctggttccatcttcaggaagctgtgggcattaaactcctttgggtagctgtgattggagactggctcaacctcgtctttaagtggattctctttggacagcgtccatactggtgggttttggatactgactactacagcaacacttccgtgcccctgataaagcagttccctgtaacctgtgagactggaccagggagcccctctggccatgccatgggcacagcaggtgtatactacgtgatggtcacatctactctttccatctttcagggaaagataaagccgacctacagatttcggtgcttgaatgtcattttgtggttgggattctgggctgtgcagctgaatgtctgtctgtcacgaatctaccttgctgctcattttcctcatcaagttgttgctggagtcctgtcaggcattgctgttgcagaaactttcagccacatccacagcatctataatgccagcctcaagaaatattttctcattaccttcttcctgttcagcttcgccatcggattttatctgctgctcaagggactgggtgtagacctcctgtggactctggagaaagcccagaggtggtgcgagcagccagaatgggtccacattgacaccacaccctttgccagcctcctcaagaacctgggcacgctctttggcctggggctggctctcaactccagcatgtacagggagagctgcaaggggaaactcagcaagtggctcccattccgcctcagctctattgtagcctccctcgtcctcctgcacgtctttgactccttgaaacccccatcccaagtcgagctggtcttctacgtcttgtccttctgcaagagtgcggtagtgcccctggcatccgtcagtgtcatcccctactgcctcgcccaggtcctgggccagccgcacaagaagtcgttgtaa',
                                '17q21.31',
                                798586,
                                799581,
                                'MEEGMNVLHDFGIQSTHYLQVNYQDSQDWFILVSVIADLRNAFYVLFPIWFHLQEAVGIKLLWVAVIGDWLNLVFKWILFGQRPYWWVLDTDYYSNTSVPLIKQFPVTCETGPGSPSGHAMGTAGVYYVMVTSTLSIFQGKIKPTYRFRCLNVILWLGFWAVQLNVCLSRIYLAAHFPHQVVAGVLSGIAVAETFSHIHSIYNASLKKYFLITFFLFSFAIGFYLLLKGLGVDLLWTLEKAQRWCEQPEWVHIDTTPFASLLKNLGTLFGLGLALNSSMYRESCKGKLSKWLPFRLSSIVASLVLLHVFDSLKPPSQVELVFYVLSFCKSAVVPLASVSVIPYCLAQVLGQPHKKSL');""")


lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(29,
                                'DLST',
                                'dihydrolipoamide S-succinyltransferase',
                                'Homo Sapiens',
                                'atgctgtcccgatcccgctgtgtgtctcgggcgttcagccgctcgctctccgccttccagaaggggaactgccctctagggagacgttccctgcctggggtctccttatgccagggaccaggttaccctaacagcaggaaggttgtcattaacaacagtgtcttcagtgttcgctttttcagaactacagctgtatgcaaggatgacttggttacagtcaaaaccccagcgtttgcagaatctgtcacagagggagatgtcaggtgggagaaagctgttggagacacagttgcagaagatgaagtggtttgtgagattgaaactgacaagacatctgtgcaggttccatcaccagcaaatggcgtgattgaagctcttttggtacctgatgggggaaaagtcgaaggaggcactccacttttcacactcaggaaaactggtgctgctcctgctaaggccaagccggctgaagctcctgctgctgcagccccaaaagcagaacctacagcagcggcagttcctccccctgcagcacccatacccactcagatgccaccggtgccctcgccctcacagcctccttctggcaaacctgtgtctgcagtaaaacccactgttgccccaccactagctgagccaggagctggcaaaggtctgcgttcagaacatcgggagaaaatgaacaggatgcggcagcgcattgctcagcgtctgaaggaggcccagaatacatgtgcaatgctgacaacttttaatgagattgacatgagtaacatccaggagatgagggctcggcacaaagaggcttttttgaagaaacataacctcaaactaggcttcatgtcggcatttgtgaaggcctcagcctttgccttgcaggaacagcctgttgtaaatgcagtgattgacgacacaaccaaagaggtggtgtatagggattatattgacatcagtgttgcagtggccaccccacggggtctggtggttccagtcatcaggaatgtggaagctatgaattttgcagatattgaacggaccatcactgaactgggagagaaggcccgaaagaatgaacttgccattgaagatatggatggcggtaccttcaccattagcaatggaggcgtttttggctcgctctttggaacacccattatcaacccccctcagtctgccatcctggggatgcatggcatctttgacaggccagtggctataggaggcaaggtagaggtgcggcccatgatgtacgtggcactgacctatgatcaccggctgattgatggcagagaggctgtgactttcctccgcaaaatcaaggcagcggtagaggatcccagagtcctcctcctggatctttag',
                                '14q24.3',
                                74881913,
                                74903743,
                                'MLSRSRCVSRAFSRSLSAFQKGNCPLGRRSLPGVSLCQGPGYPNSRKVVINNSVFSVRFFRTTAVCKDDLVTVKTPAFAESVTEGDVRWEKAVGDTVAEDEVVCEIETDKTSVQVPSPANGVIEALLVPDGGKVEGGTPLFTLRKTGAAPAKAKPAEAPAAAAPKAEPTAAAVPPPAAPIPTQMPPVPSPSQPPSGKPVSAVKPTVAPPLAEPGAGKGLRSEHREKMNRMRQRIAQRLKEAQNTCAMLTTFNEIDMSNIQEMRARHKEAFLKKHNLKLGFMSAFVKASAFALQEQPVVNAVIDDTTKEVVYRDYIDISVAVATPRGLVVPVIRNVEAMNFADIERTITELGEKARKNELAIEDMDGGTFTISNGGVFGSLFGTPIINPPQSAILGMHGIFDRPVAIGGKVEVRPMMYVALTYDHRLIDGREAVTFLRKIKAAVEDPRVLLLDL');""")


lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(30,
                                'SUCLG2',
                                'succinyl-CoA synthetase beta subunit',
                                'Homo Sapiens',
                                'atggcgtcccccgtagcagcgcaggccgggaagcttctgcgagccctagcgctgcggccccgcttcctggcggccgggtcccaggcagttcaattaacctccagaagatggctgaacctgcaggaataccagagcaagaaactgatgtctgacaacggagtgagagttcaaagattctttgtagcagacactgcaaatgaagctctcgaggctgctaagagactaaatgcaaaagaaattgttttaaaagcccagatcttagctggaggaagaggaaaaggtgtcttcaatagtggtttgaaaggaggtgttcatttaacaaaagaccctaatgttgtgggacagctggctaaacagatgattgggtacaatctagcgacaaaacaaactccaaaagaaggtgtgaaagttaacaaggtgatggttgctgaagccttggatatttccagagaaacctacctggcaattctgatggaccggtcctgcaatggccccgtgctggtgggcagcccccaggggggcgtcgacattgaagaggtggctgcttcaaacccggagctcatttttaaggagcaaattgacatttttgaaggaataaaggacagccaagctcagcggatggccgaaaatctaggcttcgttgggcctttgaaaagccaggctgcagatcaaattacgaagctgtataatctcttcctgaaaattgatgctactcaggtggaagtgaatccctttggtgaaactccagaaggacaagttgtctgttttgatgccaagataaactttgatgacaacgcagaattccgacaaaaagacatatttgctatggacgacaaatcagagaatgagcccattgaaaatgaagctgccaaatatgatctaaaatacataggactagatgggaacattgcctgctttgtgaatggtgctgggctcgccatggctacttgtgatatcattttccttaatggtgggaagccagccaacttcttggatcttggaggtggtgtaaaggaagctcaagtatatcaagcattcaaattgctcacagctgatcctaaggttgaagccatccttgtcaatatatttggtggtatcgtcaactgtgccatcattgccaatgggatcaccaaagcctgccgggagctagaactcaaggtgcccctggtggtccggcttgaaggaaccaacgtccaagaggcccagaagatactcaacaacagcggactccccattacttcagccattgacctggaggatgcagccaagaaggctgtggccagtgtggccaagaagtga',
                                '3p14.1',
                                67360460,
                                67654614,
                                'MASPVAAQAGKLLRALALRPRFLAAGSQAVQLTSRRWLNLQEYQSKKLMSDNGVRVQRFFVADTANEALEAAKRLNAKEIVLKAQILAGGRGKGVFNSGLKGGVHLTKDPNVVGQLAKQMIGYNLATKQTPKEGVKVNKVMVAEALDISRETYLAILMDRSCNGPVLVGSPQGGVDIEEVAASNPELIFKEQIDIFEGIKDSQAQRMAENLGFVGPLKSQAADQITKLYNLFLKIDATQVEVNPFGETPEGQVVCFDAKINFDDNAEFRQKDIFAMDDKSENEPIENEAAKYDLKYIGLDGNIACFVNGAGLAMATCDIIFLNGGKPANFLDLGGGVKEAQVYQAFKLLTADPKVEAILVNIFGGIVNCAIIANGITKACRELELKVPLVVRLEGTNVQEAQKILNNSGLPITSAIDLEDAAKKAVASVAKK');""")


lab4.commit()

##### 1.3.2 Drosophila melanogaster
1.3.2.1
https://www.genome.jp/dbget-bin/www_bget?dme:Dmel_CG14740+dme:Dmel_CG3861
https://www.ncbi.nlm.nih.gov/nuccore/NT_033777.3?report=genbank&from=12061070&to=12062944&strand=true
1.3.2.2
https://www.genome.jp/dbget-bin/www_bget?dme:Dmel_CG5432+dme:Dmel_CG6058
https://www.ncbi.nlm.nih.gov/nuccore/NT_037436.4?report=genbank&from=16954822&to=16968724
1.3.2.3
https://www.genome.jp/dbget-bin/www_bget?dme:Dmel_CG5214
https://www.ncbi.nlm.nih.gov/nuccore/NT_033779.5?report=genbank&from=2814336&to=2815760&strand=true
1.3.2.4
https://www.genome.jp/dbget-bin/www_bget?dme:Dmel_CG10622+dme:Dmel_CG1065+dme:Dmel_CG11963+dme:Dmel_CG6255
https://www.ncbi.nlm.nih.gov/nuccore/NT_037436.4?report=genbank&from=3814211&to=3818383

In [40]:
lab = lab4.cursor()
lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(31,
                                'CG14740',
                                'citrate synthase',
                                'Drosophila melanogaster',
                                'atgcaaaaaaccaataactacaaaagcttcaaaatcttcttcaagaacgttccatttcgttcatatcccgactgcaagaatggtaaaggttcaggcctaaaagccaagttggcaaagaaaattcctatagaacgtgaaaagtttttgggtataaagtgtctgcacggcaagaagataattggccagatcagtgttaatagcgtgattggaggaatgcgaggacttccacttttgttttgcgagacatccagcttggacaaaaacaagggtatttattaccgtggaaaactgcttaaggatgtgtgtgccaaactgccacgggtgcaagagggcacacaagagggcactcccgaaggatgtttcttcctgctgaccagcggatcgatgcccacgaagaaggaggcacaggaagtgaccaacgagtggctgaagcggggctcagttccgcgctactgcctccggatgatcgactccatggacaagcgggtgcatccgatggcccaattgtgcgccgccagtgcctgtctcaatccgcagagccagttcgtcgaggcttacaccaaaggggccagacgtgcagactactggaaatactcctacgaggattcaatgaacctcatcgccatgctgcccaccgtggcggctgccatctattctaacgtgtttagggatggcgaaggttcacgggaggtcaactatgaggaggactggtccggcaacttctgccgcatgcttggactacccgaaaaggatttcgttgatcttatgcggctctacatgatcctgcatgcagatcatgagagcggcaatgtttccgcccatgcttgccacctagtcggaacggcgctcagcgatcccttcctgtctttctcggccagcatgtgcggcctggctgggccacttcatggtttggccaatcaggaagtgctggtttggctgacaaagcttaggaaggccattggcgatgacccctccgatgaagagctaaagaagttcatcgatgatacgctgaaagggggccaggtcattcccggctacggacacgctgtccttcgggacaccgatcctcggttcgtcctgcaaaacgagtttgccatgaagcactgcaaggatgatccaggcgtaaagctggtgacccgcctgtggaagatcataccagaggtgctcaagaagctcaacaaggtagcgaatccgtatccaaacgtcgatgcccattcgggcgtcctgctgcaacattactgtctgaaggagctgaagttctacacagttcttttcggagtttctcgggcgcttggagttctgtcccagctgatttggtccagggctttgggagccccaattgaaagaccaaagtcattttcctccatcgagatctgcaaattcatcaatgaagcagacaaaaaggcaggaaaaaagaacaataagaaaaagtgctag',
                                '3R',
                                12061070,
                                12062944,
                                'MQKTNNYKSFKIFFKNVPFRSYPDCKNGKGSGLKAKLAKKIPIEREKFLGIKCLHGKKIIGQISVNSVIGGMRGLPLLFCETSSLDKNKGIYYRGKLLKDVCAKLPRVQEGTQEGTPEGCFFLLTSGSMPTKKEAQEVTNEWLKRGSVPRYCLRMIDSMDKRVHPMAQLCAASACLNPQSQFVEAYTKGARRADYWKYSYEDSMNLIAMLPTVAAAIYSNVFRDGEGSREVNYEEDWSGNFCRMLGLPEKDFVDLMRLYMILHADHESGNVSAHACHLVGTALSDPFLSFSASMCGLAGPLHGLANQEVLVWLTKLRKAIGDDPSDEELKKFIDDTLKGGQVIPGYGHAVLRDTDPRFVLQNEFAMKHCKDDPGVKLVTRLWKIIPEVLKKLNKVANPYPNVDAHSGVLLQHYCLKELKFYTVLFGVSRALGVLSQLIWSRALGAPIERPKSFSSIEICKFINEADKKAGKKNNKKKC');""")

lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(32,
                                'Nc73EF',
                                '2-oxoglutarate dehydrogenase E1 component',
                                'Drosophila melanogaster',
                                'atgcatagagcccacacagccttcagcctggccttgtcgccgatggcgcacaagaacttcgccacatggctgctcaagagcagcagcagtcagcagatggccaaggtaactgcagcggccgctgtgcgcacctacaactccgcagctgccgaaccttttgccaacggcagcaccgcctcctacgtggaggagatgtacaacgcctggcttcgggatcccacttccgtgcacacctcctgggacgcgtacttccgcagcaacagctacgttagcccgcccaacttggcgcccgtgcaggccaacactctgccgctgaccgccttcaactttggaggagccgtcgccggcgctgcgcccgactccaagaccattgacgaccatctggccgtccaggccatcatcaggagctaccagattcgaggacataatattgctcacctcgatccacttgaaattaatacaccagaattgcctggcaactcctcgacgaaatccatttacgctaatttcagttttggcgagcaggacatggatcgccagttcaagctgcccagcactaccttcatcggaggcgatgaggcttcgttgcccctaaaggaaatcctgaaccgcctggagaatgtctactgtaataagattggcgtggagttcatgttcatcaactctctggagcaatgcaactggatccgcaagcgttttgagacccccggcgtccttaacttctcgcccgaggagaagcgtctgatcctggcccgtttgacccgtgccaccggctttgaggctttcctggccaagaagtactcttctgagaaacgtttcggtctggagggttgcgagatcatgatcccagccctgaaggagatcatcgacgtatcaacggagttgggagtggagtcggtcatcatgggcatgccccatcgtggacgtcttaacaccttggccaatgtatgccgcaagcccttgaaccagatcttcacccagttcgctggactggaggctgctgatgatggctctggtgatgtcaagtaccatctcggtacatacatcgagcgattgaaccgcgttacaaacaagaacatccgcctggctgtcgtggccaacccgtcccatctggaggctgtggatcccgtggtgcagggcaagacccgtgccgagcagttctaccgtggcgaccaggagggcaagaaggttatgtccattttgatccacggtgatgccgccttctgcggacagggcgtcgtctatgaaactatgcatctttcggacctgcccgactacaccacccacggaactatccatgtggtggccaacaaccagatcggtttcaccaccgatccccgtttctcgaggtcctctccctactgtacggatgtggctcgtgtcgtcaatgctcctattttccacgtcaacgctgacgatccagaggccgtgatgcatgtgtgcaaggtggctgctgagtggcgtgctactttccacaaggattgtgttattgatttggtcggataccgccgcaatggacacaacgagatcgacgagcccatgttcacgcaacccttgatgtaccagaagatccgcaagcacaagaactgtctcgacctgtatgccgacaaactgatcgccgagggcactgtcaccgccgaggaggttaagtcggttgccgctaaatacgagaacatttgcgaggaggcattcgctctggccaagaccgagacccacgtcaagtacaaggactggctcgactcgccctggtccggctttttcgagggcaaagacccattgaaggtagcgcccactggagtgaaggaggagaccctcatccacatcggcaaccgcttctcgtcgccaccaccgaacgctgctgaattcgtgattcacaagggtctattgcgagtgttggccgctcgcaaggcaatggtggacgaaaaggtcgctgattgggctttgggagaggccatggccttcggctctctgctgaaggagggaatccatgtgcgcctttcgggacaggatgtcgagcgtggtaccttctcgcatcgccaccatgtgctgcaccaccagctggtcgacaaggccacttacaactcgctgcagcacatgtacccagatcaggcgccctactccgtctccaacagctcgctgtcggagtacgcagtgcttggtttcgagcacggttactcgatgaccaatcccaatgccctggtgctgtgggaggctcagttcggagacttcagcaacacggcccagtcgatcatcgatcagttcatctccagcggtcagtcaaagtgggtgcgccaatcgggtctggtaatgctcctgccccacggcatggaaggcatgggccccgagcactcctcgtgccgcgtggagcgcttcctgcaaatgagcagtgacgatcccgactacttcccaccagagtccgatgagttcggagtgcgacagctgcacgacattaactggatcgtggcaaactgctcgacgcccgccaactactaccacatcctgcgccgacagatcgcattgcctttccgcaagcccctgattctgtgcacgcccaaatcgctgctgcgtcaccccgaggctaagagtcctttcagcgagatgagcgagggcagcgagttccagcgcatcatccccgacaacggtcccgccggccagaatcccagcaatgtgaagaaggtcgtcttctgctcgggccgcgtctactacgatttgaccaagacacgtagggaaaagcagctggagggcgaaatcgccattgtgcgcgtggagcagatctctcccttccccttcgatctggtcaaggagcaggccaacctgtacaagaatgccgaactcgtgtgggcccaagaggagcacaagaaccagggcagctggacctatgtgcaacctcgtttcctcaccgccttgaaccacagccgcgacgtcagccaaagcgatgaacaatcctcctccaccaatactaccactactactgatcatactaatcatgaatccgacaccgattccgattcaaaatctaaaccgtggctgagtcgcatgttcgccgccccgaactcctcgaccggcggcgatcctaaggatccggcgcaaacccttggcggcgacttcaatgccgccaagcactttgacttaaagaatgtacgacacgatttcaataggcccgcgggcatcgcggccgctccgggcgcccgcatagcgaaaaccggacgcaaaattagctacgtcggacgcgcctgcggagcctccaccgccaccggatccaaggcccagcacatccgtgagctgaatgcgctgctcaacgacgcgatttcgacctaa',
                                '3L',
                                16954822,
                                16968724,
                                'MHRAHTAFSLALSPMAHKNFATWLLKSSSSQQMAKVTAAAAVRTYNSAAAEPFANGSTASYVEEMYNAWLRDPTSVHTSWDAYFRSNSYVSPPNLAPVQANTLPLTAFNFGGAVAGAAPDSKTIDDHLAVQAIIRSYQIRGHNIAHLDPLEINTPELPGNSSTKSIYANFSFGEQDMDRQFKLPSTTFIGGDEASLPLKEILNRLENVYCNKIGVEFMFINSLEQCNWIRKRFETPGVLNFSPEEKRLILARLTRATGFEAFLAKKYSSEKRFGLEGCEIMIPALKEIIDVSTELGVESVIMGMPHRGRLNTLANVCRKPLNQIFTQFAGLEAADDGSGDVKYHLGTYIERLNRVTNKNIRLAVVANPSHLEAVDPVVQGKTRAEQFYRGDQEGKKVMSILIHGDAAFCGQGVVYETMHLSDLPDYTTHGTIHVVANNQIGFTTDPRFSRSSPYCTDVARVVNAPIFHVNADDPEAVMHVCKVAAEWRATFHKDCVIDLVGYRRNGHNEIDEPMFTQPLMYQKIRKHKNCLDLYADKLIAEGTVTAEEVKSVAAKYENICEEAFALAKTETHVKYKDWLDSPWSGFFEGKDPLKVAPTGVKEETLIHIGNRFSSPPPNAAEFVIHKGLLRVLAARKAMVDEKVADWALGEAMAFGSLLKEGIHVRLSGQDVERGTFSHRHHVLHHQLVDKATYNSLQHMYPDQAPYSVSNSSLSEYAVLGFEHGYSMTNPNALVLWEAQFGDFSNTAQSIIDQFISSGQSKWVRQSGLVMLLPHGMEGMGPEHSSCRVERFLQMSSDDPDYFPPESDEFGVRQLHDINWIVANCSTPANYYHILRRQIALPFRKPLILCTPKSLLRHPEAKSPFSEMSEGSEFQRIIPDNGPAGQNPSNVKKVVFCSGRVYYDLTKTRREKQLEGEIAIVRVEQISPFPFDLVKEQANLYKNAELVWAQEEHKNQGSWTYVQPRFLTALNHSRDVSQSDEQSSSTNTTTTTDHTNHESDTDSDSKSKPWLSRMFAAPNSSTGGDPKDPAQTLGGDFNAAKHFDLKNVRHDFNRPAGIAAAPGARIAKTGRKISYVGRACGASTATGSKAQHIRELNALLNDAIST');""")


lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(33,
                                'CG5214',
                                '2-oxoglutarate dehydrogenase E2 component (dihydrolipoamide succinyltransferase)',
                                'Drosophila melanogaster',
                                'atgacgggaataatttcgatcgtaacgagacggctgccccaaactttgggaatgcgagccctgcggagtaatgaggtaaagcgctgcatccgccaatattctcggttagttgcctgcgccgcccagcagcagcaactgcttcgccaggatggctcgaatcgctgccaggaggccaccaggcttctcacctggcagggaatccacaccacgtcgagcttgtggtcggagcagaccgtcaatgtgccaccctttgcggactccattgccgagggtgacatcaagtttacttgcaaggtgggtgactcattcgccgctgacgaggctgtcatggaaatcgagaccgacaagacgacggtggctgtgccagctcccttctccggaactctaaccgacattctggtgaaggatggcgacaccgtcaagcccggccaggctctgttcaagatcaagcccggtgcagcgcccgccaaggcagctgctccagcggctgctcctgcgcctgctgccccaaaagcagcaccagctccagctgctgcacccaagccggcacctccaccacctgcggccggcgcaccaaagccaccaccaccgccaccaccaaaggcagcccctcgaccaccgccacctgctccagtggctgcactcaaaccggccgtcgcccaggtgaaggtgccaccagcggacggatcgcggcagatcctaggcactaggtccgagcagcgtgtcaagatgaaccgcatgcgtctaaagattgccgcccgcttgaaggatgcccagaacacatgtgccatgctcaccactttcaacgaggttgatatgagctatgccatggacttccgaaagcagaatctggatgcgttcactaagaagtatggtattaagtttggattcatgtcgatcttcgccaaggctagtgcctatgcgctgcaggatcagcccgtagtgaacgccgtcatcgatggcacggacatcgtgtatcgcgactacgttgacatctctgtggccgtggctacgccccgtggattggtggtacccgtcatccgcaacgtggagggcatgaactatgcggacatcgagatcgcactggccggtctggccgataaggccaggcgtgatgccatcaccgtggaggacatggacggtggcaccttcaccatcagcaatggcggagtgttcggatccctgatgggcacgcccatcatcaatccgccacagagtgccattctcggcatgcacggcatctttgagcggccaattgctgtcaagggagaggtcaagatacgtcctatgatgtacatcgccctgacctacgatcaccgaatcattgatggacgtgaggcggtcctgttcctgcgaaaaataaaggctgccgtagagaacccagcaataattgttgccggattgtaa',
                                '3R',
                                11244302,
                                11246862,
                                'MTGIISIVTRRLPQTLGMRALRSNEVKRCIRQYSRLVACAAQQQQLLRQDGSNRCQEATRLLTWQGIHTTSSLWSEQTVNVPPFADSIAEGDIKFTCKVGDSFAADEAVMEIETDKTTVAVPAPFSGTLTDILVKDGDTVKPGQALFKIKPGAAPAKAAAPAAAPAPAAPKAAPAPAAAPKPAPPPPAAGAPKPPPPPPPKAAPRPPPPAPVAALKPAVAQVKVPPADGSRQILGTRSEQRVKMNRMRLKIAARLKDAQNTCAMLTTFNEVDMSYAMDFRKQNLDAFTKKYGIKFGFMSIFAKASAYALQDQPVVNAVIDGTDIVYRDYVDISVAVATPRGLVVPVIRNVEGMNYADIEIALAGLADKARRDAITVEDMDGGTFTISNGGVFGSLMGTPIINPPQSAILGMHGIFERPIAVKGEVKIRPMMYIALTYDHRIIDGREAVLFLRKIKAAVENPAIIVAGL');""")


lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(34,
                                'ScsbetaG',
                                'succinyl-CoA synthetase beta subunit',
                                'Drosophila melanogaster',
                                'atggctgcttcaatgagggcgctgctgaaagtgcgagatggcttcgtggccggagtgcgctgcaattcgcagtacaacaagacgcgcggcaacttgaagctgaacggcgattcgcgggtgatctgccagggattcaccggcaaacagggcacgttccacagccaacaggctctggagtacggcaccaagttggtcggcggcatttcccccaagaagggaggcacccagcatctgggactgcccgtcttcgcttcggtggcggaggccaagaaggccaccgatccacatgccaccgtcatctatgtgccaccaccgggcgctgcggccgccatcatcgaggctctggaagcggagatccccctgatcgtttgcattacggagggtgtgccgcagcacgacatggtgaaggtgaagcacgccctcatcagccagagcaagtcgcgattggtgggtcccaactgcccgggaatcatcgcccccgaacagtgcaagatcggcatcatgccgggtcacattcacaagcgcggcaagatcggcgtggtctcgcgctcgggaaccttgacctacgaggccgtgcaccagaccacggaggtgggtctgggccagaccctgtgcgtgggcattggaggcgatccgttcaacggaaccgacttcatcgactgcctggaggtcttcctcaaggatcccgagaccaagggcatcatcctgatcggcgagatcggaggcgttgccgaggagaaggctgccgactacctgaccgagtacaattcgggcatcaaggccaagcctgtcgtctcgttcattgccggagtgtcggcgccacccggccgtcgcatgggtcacgctggagccatcatttccggaggaaagggaggtgccaacgacaagatcgccgccctggagaaggccggcgtcattgtgaccaggagtcctgccaaaatgggccacgagctcttcaaggagatgaagcgtctggagttagtgtaa',
                                '3L',
                                3814211,
                                3818383,
                                'MAASMRALLKVRDGFVAGVRCNSQYNKTRGNLKLNGDSRVICQGFTGKQGTFHSQQALEYGTKLVGGISPKKGGTQHLGLPVFASVAEAKKATDPHATVIYVPPPGAAAAIIEALEAEIPLIVCITEGVPQHDMVKVKHALISQSKSRLVGPNCPGIIAPEQCKIGIMPGHIHKRGKIGVVSRSGTLTYEAVHQTTEVGLGQTLCVGIGGDPFNGTDFIDCLEVFLKDPETKGIILIGEIGGVAEEKAADYLTEYNSGIKAKPVVSFIAGVSAPPGRRMGHAGAIISGGKGGANDKIAALEKAGVIVTRSPAKMGHELFKEMKRLELV');""")

lab4.commit()

##### 1.3.3 Escherichia coli
1.3.3.1
https://www.genome.jp/dbget-bin/www_bget?eco:b0720
1.3.3.2
https://www.genome.jp/dbget-bin/www_bget?eco:b0726
1.3.3.3
https://www.genome.jp/dbget-bin/www_bget?eco:b0727

In [41]:
lab = lab4.cursor()
lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(35,
                                'gltA',
                                'citrate synthase',
                                'Escherichia coli',
                                'atggctgatacaaaagcaaaactcaccctcaacggggatacagctgttgaactggatgtgctgaaaggcacgctgggtcaagatgttattgatatccgtactctcggttcaaaaggtgtgttcacctttgacccaggcttcacttcaaccgcatcctgcgaatctaaaattacttttattgatggtgatgaaggtattttgctgcaccgcggtttcccgatcgatcagctggcgaccgattctaactacctggaagtttgttacatcctgctgaatggtgaaaaaccgactcaggaacagtatgacgaatttaaaactacggtgacccgtcataccatgatccacgagcagattacccgtctgttccatgctttccgtcgcgactcgcatccaatggcagtcatgtgtggtattaccggcgcgctggcggcgttctatcacgactcgctggatgttaacaatcctcgtcaccgtgaaattgccgcgttccgcctgctgtcgaaaatgccgaccatggccgcgatgtgttacaagtattccattggtcagccatttgtttacccgcgcaacgatctctcctacgccggtaacttcctgaatatgatgttctccacgccgtgcgaaccgtatgaagttaatccgattctggaacgtgctatggaccgtattctgatcctgcacgctgaccatgaacagaacgcctctacctccaccgtgcgtaccgctggctcttcgggtgcgaacccgtttgcctgtatcgcagcaggtattgcttcactgtggggacctgcgcacggcggtgctaacgaagcggcgctgaaaatgctggaagaaatcagctccgttaaacacattccggaatttgttcgtcgtgcgaaagacaaaaatgattctttccgcctgatgggcttcggtcaccgcgtgtacaaaaattacgacccgcgcgccaccgtaatgcgtgaaacctgccatgaagtgctgaaagagctgggcacgaaggatgacctgctggaagtggctatggagctggaaaacatcgcgctgaacgacccgtactttatcgagaagaaactgtacccgaacgtcgatttctactctggtatcatcctgaaagcgatgggtattccgtcttccatgttcaccgtcattttcgcaatggcacgtaccgttggctggatcgcccactggagcgaaatgcacagtgacggtatgaagattgcccgtccgcgtcagctgtatacaggatatgaaaaacgcgactttaaaagcgatatcaagcgttaa',
                                'circular',
                                753185,
                                754468,
                                'MADTKAKLTLNGDTAVELDVLKGTLGQDVIDIRTLGSKGVFTFDPGFTSTASCESKITFIDGDEGILLHRGFPIDQLATDSNYLEVCYILLNGEKPTQEQYDEFKTTVTRHTMIHEQITRLFHAFRRDSHPMAVMCGITGALAAFYHDSLDVNNPRHREIAAFRLLSKMPTMAAMCYKYSIGQPFVYPRNDLSYAGNFLNMMFSTPCEPYEVNPILERAMDRILILHADHEQNASTSTVRTAGSSGANPFACIAAGIASLWGPAHGGANEAALKMLEEISSVKHIPEFVRRAKDKNDSFRLMGFGHRVYKNYDPRATVMRETCHEVLKELGTKDDLLEVAMELENIALNDPYFIEKKLYPNVDFYSGIILKAMGIPSSMFTVIFAMARTVGWIAHWSEMHSDGMKIARPRQLYTGYEKRDFKSDIKR');""")


lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(36,
                                'sucA',
                                '2-oxoglutarate dehydrogenase E1 component',
                                'Escherichia coli',
                                'atgcagaacagcgctttgaaagcctggttggactcttcttacctctctggcgcaaaccagagctggatagaacagctctatgaagacttcttaaccgatcctgactcggttgacgctaactggcgttcgacgttccagcagttacctggtacgggagtcaaaccggatcaattccactctcaaacgcgtgaatatttccgccgcctggcgaaagacgcttcacgttactcttcaacgatctccgaccctgacaccaatgtgaagcaggttaaagtcctgcagctcattaacgcataccgcttccgtggtcaccagcatgcgaatctcgatccgctgggactgtggcagcaagataaagtggccgatctggatccgtctttccacgatctgaccgaagcagacttccaggagaccttcaacgtcggttcatttgccagcggcaaagaaaccatgaaactcggcgagctgctggaagccctcaagcaaacctactgcggcccgattggtgccgagtatatgcacattaccagcaccgaagaaaaacgctggatccaacagcgtatcgagtctggtcgcgcgactttcaatagcgaagagaaaaaacgcttcttaagcgaactgaccgccgctgaaggtcttgaacgttacctcggcgcaaaattccctggcgcaaaacgcttctcgctggaaggcggtgacgcgttaatcccgatgcttaaagagatgatccgccacgctggcaacagcggcacccgcgaagtggttctcgggatggcgcaccgtggtcgtctgaacgtgctggtgaacgtgctgggtaaaaaaccgcaagacttgttcgacgagttcgccggtaaacataaagaacacctcggcacgggtgacgtgaaataccacatgggcttctcgtctgacttccagaccgatggcggcctggtgcacctggcgctggcgtttaacccgtctcaccttgagattgtaagcccggtagttatcggttctgttcgtgcccgtctggacagacttgatgagccgagcagcaacaaagtgctgccaatcaccatccacggtgacgccgcagtgaccgggcagggcgtggttcaggaaaccctgaacatgtcgaaagcgcgtggttatgaagttggcggtacggtacgtatcgttatcaacaaccaggttggtttcaccacctctaatccgctggatgcccgttctacgccgtactgtactgatatcggtaagatggttcaggccccgattttccacgttaacgcggacgatccggaagccgttgcctttgtgacccgtctggcgctcgatttccgtaacacctttaaacgtgatgtcttcatcgacctggtgtgctaccgccgtcacggccacaacgaagccgacgagccgagcgcaacccagccgctgatgtatcagaaaatcaaaaaacatccgacaccgcgcaaaatctacgctgacaagctggagcaggaaaaagtggcgacgctggaagatgccaccgagatggttaacctgtaccgcgatgcgctggatgctggcgattgcgtagtggcagagtggcgtccgatgaacatgcactctttcacctggtcgccgtacctcaaccacgaatgggacgaagagtacccgaacaaagttgagatgaagcgcctgcaggagctggcgaaacgcatcagcacggtgccggaagcagttgaaatgcagtctcgcgttgccaagatttatggcgatcgccaggcgatggctgccggtgagaaactgttcgactggggcggtgcggaaaacctcgcttacgccacgctggttgatgaaggcattccggttcgcctgtcgggtgaagactccggtcgcggtaccttcttccaccgccacgcggtgatccacaaccagtctaacggttccacttacacgccgctgcaacatatccataacgggcagggcgcgttccgtgtctgggactccgtactgtctgaagaagcagtgctggcgtttgaatatggttatgccaccgcagaaccacgcactctgaccatctgggaagcgcagttcggtgacttcgccaacggtgcgcaggtggttatcgaccagttcatctcctctggcgaacagaaatggggccggatgtgtggtctggtgatgttgctgccgcacggttacgaagggcaggggccggagcactcctccgcgcgtctggaacgttatctgcaactttgtgctgagcaaaacatgcaggtttgcgtaccgtctaccccggcacaggtttaccacatgctgcgtcgtcaggcgctgcgcgggatgcgtcgtccgctggtcgtgatgtcgccgaaatccctgctgcgtcatccgctggcggtttccagcctcgaagaactggcgaacggcaccttcctgccagccatcggtgaaatcgacgagcttgatccgaagggcgtgaagcgcgtagtgatgtgttctggtaaggtttattacgacctgctggaacagcgtcgtaagaacaatcaacacgatgtcgccattgtgcgtatcgagcaactctacccgttcccgcataaagcgatgcaggaagtgttgcagcagtttgctcacgtcaaggattttgtctggtgccaggaagagccgctcaaccagggcgcatggtactgcagccagcatcatttccgtgaagtgattccgtttggggcttctctgcgttatgcaggccgcccggcctccgcctctccggcggtagggtatatgtccgttcaccagaaacagcaacaagatctggttaatgacgcgctgaacgtcgaataa',
                                'circular',
                                758706,
                                761507,
                                'MQNSALKAWLDSSYLSGANQSWIEQLYEDFLTDPDSVDANWRSTFQQLPGTGVKPDQFHSQTREYFRRLAKDASRYSSTISDPDTNVKQVKVLQLINAYRFRGHQHANLDPLGLWQQDKVADLDPSFHDLTEADFQETFNVGSFASGKETMKLGELLEALKQTYCGPIGAEYMHITSTEEKRWIQQRIESGRATFNSEEKKRFLSELTAAEGLERYLGAKFPGAKRFSLEGGDALIPMLKEMIRHAGNSGTREVVLGMAHRGRLNVLVNVLGKKPQDLFDEFAGKHKEHLGTGDVKYHMGFSSDFQTDGGLVHLALAFNPSHLEIVSPVVIGSVRARLDRLDEPSSNKVLPITIHGDAAVTGQGVVQETLNMSKARGYEVGGTVRIVINNQVGFTTSNPLDARSTPYCTDIGKMVQAPIFHVNADDPEAVAFVTRLALDFRNTFKRDVFIDLVCYRRHGHNEADEPSATQPLMYQKIKKHPTPRKIYADKLEQEKVATLEDATEMVNLYRDALDAGDCVVAEWRPMNMHSFTWSPYLNHEWDEEYPNKVEMKRLQELAKRISTVPEAVEMQSRVAKIYGDRQAMAAGEKLFDWGGAENLAYATLVDEGIPVRLSGEDSGRGTFFHRHAVIHNQSNGSTYTPLQHIHNGQGAFRVWDSVLSEEAVLAFEYGYATAEPRTLTIWEAQFGDFANGAQVVIDQFISSGEQKWGRMCGLVMLLPHGYEGQGPEHSSARLERYLQLCAEQNMQVCVPSTPAQVYHMLRRQALRGMRRPLVVMSPKSLLRHPLAVSSLEELANGTFLPAIGEIDELDPKGVKRVVMCSGKVYYDLLEQRRKNNQHDVAIVRIEQLYPFPHKAMQEVLQQFAHVKDFVWCQEEPLNQGAWYCSQHHFREVIPFGASLRYAGRPASASPAVGYMSVHQKQQQDLVNDALNVE');""")


lab.execute("""INSERT INTO genes(id,
                               name,
                               description,
                               organism,
                               nucleotide_sequence,
                               chromosome,
                               start,
                               end,
                               aa)
                         VALUES(37,
                                'sucB',
                                '2-oxoglutarate dehydrogenase E2 component (dihydrolipoamide succinyltransferase)',
                                'Escherichia coli',
                                'atgagtagcgtagatattctggtccctgacctgcctgaatccgtagccgatgccaccgtcgcaacctggcataaaaaacccggcgacgcagtcgtacgtgatgaagtgctggtagaaatcgaaactgacaaagtggtactggaagtaccggcatcagcagacggcattctggatgcggttctggaagatgaaggtacaacggtaacgtctcgtcagatccttggtcgcctgcgtgaaggcaacagcgccggtaaagaaaccagcgccaaatctgaagagaaagcgtccactccggcgcaacgccagcaggcgtctctggaagagcaaaacaacgatgcgttaagcccggcgatccgtcgcctgctggctgaacacaatctcgacgccagcgccattaaaggcaccggtgtgggtggtcgtctgactcgtgaagatgtggaaaaacatctggcgaaagccccggcgaaagagtctgctccggcagcggctgctccggcggcgcaaccggctctggctgcacgtagtgaaaaacgtgtcccgatgactcgcctgcgtaagcgtgtggcagagcgtctgctggaagcgaaaaactccaccgccatgctgaccacgttcaacgaagtcaacatgaagccgattatggatctgcgtaagcagtacggtgaagcgtttgaaaaacgccacggcatccgtctgggctttatgtccttctacgtgaaagcggtggttgaagccctgaaacgttacccggaagtgaacgcttctatcgacggcgatgacgtggtttaccacaactatttcgacgtcagcatggcggtttctacgccgcgcggcctggtgacgccggttctgcgtgatgtcgataccctcggcatggcagacatcgagaagaaaatcaaagagctggcagtcaaaggccgtgacggcaagctgaccgttgaagatctgaccggtggtaacttcaccatcaccaacggtggtgtgttcggttccctgatgtctacgccgatcatcaacccgccgcagagcgcaattctgggtatgcacgctatcaaagatcgtccgatggcggtgaatggtcaggttgagatcctgccgatgatgtacctggcgctgtcctacgatcaccgtctgatcgatggtcgcgaatccgtgggcttcctggtaacgatcaaagagttgctggaagatccgacgcgtctgctgctggacgtgtag',
                                'circular',
                                761522,
                                762739,
                                'MSSVDILVPDLPESVADATVATWHKKPGDAVVRDEVLVEIETDKVVLEVPASADGILDAVLEDEGTTVTSRQILGRLREGNSAGKETSAKSEEKASTPAQRQQASLEEQNNDALSPAIRRLLAEHNLDASAIKGTGVGGRLTREDVEKHLAKAPAKESAPAAAAPAAQPALAARSEKRVPMTRLRKRVAERLLEAKNSTAMLTTFNEVNMKPIMDLRKQYGEAFEKRHGIRLGFMSFYVKAVVEALKRYPEVNASIDGDDVVYHNYFDVSMAVSTPRGLVTPVLRDVDTLGMADIEKKIKELAVKGRDGKLTVEDLTGGNFTITNGGVFGSLMSTPIINPPQSAILGMHAIKDRPMAVNGQVEILPMMYLALSYDHRLIDGRESVGFLVTIKELLEDPTRLLLDV');""")




lab4.commit()

### 2. create a table for enzyme

In [42]:
lab = lab4.cursor()

lab.execute("""CREATE TABLE enzyme(id INT,
                                name TEXT,
                                function TEXT,
                                EC TEXT);""")

#### 2.1  Pentose phosphate pathway

In [43]:
lab.execute("""INSERT INTO enzyme(id,
                                 name,
                                 function,
                                 EC)
                         VALUES(1,
                                'glucose-6-phosphate dehydrogenase',
                                'This protein is a cytosolic enzyme encoded by a housekeeping X-linked gene whose main function is to produce NADPH, a key electron donor in the defense against oxidizing agents and in reductive biosynthetic reactions.',
                                '1.1.1.49 & 1.1.1.363');""")

lab.execute("""INSERT INTO enzyme(id,
                                 name,
                                 function,
                                 EC)
                         VALUES(2,
                                'glucose-6-phosphate isomerase',
                                'The encoded protein has been identified as a moonlighting protein based on its ability to perform mechanistically distinct functions. In the cytoplasm, the gene product functions as a glycolytic enzyme (glucose-6-phosphate isomerase) that interconverts glucose-6-phosphate and fructose-6-phosphate. Extracellularly, the encoded protein (also referred to as neuroleukin) functions as a neurotrophic factor that promotes survival of skeletal motor neurons and sensory neurons, and as a lymphokine that induces immunoglobulin secretion. The encoded protein is also referred to as autocrine motility factor based on an additional function as a tumor-secreted cytokine and angiogenic factor. Defects in this gene are the cause of nonspherocytic hemolytic anemia and a severe enzyme deficiency can be associated with hydrops fetalis, immediate neonatal death and neurological impairment. Alternative splicing results in multiple transcript variants.',
                                '5.3.1.9');""")

lab.execute("""INSERT INTO enzyme(id,
                                 name,
                                 function,
                                 EC)
                         VALUES(3,
                                'hexose-6-phosphate dehydrogenase/glucose 1-dehydrogenase/6-phosphogluconolactonase',
                                'There are 2 forms of glucose-6-phosphate dehydrogenase. G form is X-linked and H form, encoded by this gene, is autosomally linked. This H form shows activity with other hexose-6-phosphates, especially galactose-6-phosphate, whereas the G form is specific for glucose-6-phosphate. Both forms are present in most tissues, but H form is not found in red cells.',
                                '1.1.1.47 & 3.1.1.31');""")

lab.execute("""INSERT INTO enzyme(id,
                                 name,
                                 function,
                                 EC)
                         VALUES(4,
                                '6-phosphogluconate dehydrogenase',
                                '6-phosphogluconate dehydrogenase is the second dehydrogenase in the pentose phosphate shunt. Deficiency of this enzyme is generally asymptomatic, and the inheritance of this disorder is autosomal dominant. Hemolysis results from combined deficiency of 6-phosphogluconate dehydrogenase and 6-phosphogluconolactonase suggesting a synergism of the two enzymopathies.',
                                '1.1.1.44 & 1.1.1.343');""")
lab4.commit()

#### 2.2 Glycolysis / Gluconeogenesis
https://www.genome.jp/dbget-bin/www_bget?hsa:5236+hsa:55276
https://www.genome.jp/dbget-bin/www_bget?hsa:226+hsa:229+hsa:230
https://www.genome.jp/dbget-bin/www_bget?ec:3.1.3.9

In [44]:
lab = lab4.cursor()
lab.execute("""INSERT INTO enzyme(id,
                                 name,
                                 function,
                                 EC)
                         VALUES(5,
                                'phosphoglucomutase 1',
                                'Maximum activity is only obtained in the presence of alpha-D-glucose 1,6-bisphosphate. This bisphosphate is an intermediate in the reaction, being formed by transfer of a phosphate residue from the enzyme to the substrate, but the dissociation of bisphosphate from the enzyme complex is much slower than the overall isomerization. The enzyme also catalyses (more slowly) the interconversion of 1-phosphate and 6-phosphate isomers of many other alpha-D-hexoses, and the interconversion of alpha-D-ribose 1-phosphate and 5-phosphate, phosphoglucomutase (glucose-cofactor).',
                                '5.4.2.2');""")

lab.execute("""INSERT INTO enzyme(id,
                                 name,
                                 function,
                                 EC)
                         VALUES(6,
                                'fructose-bisphosphate aldolase',
                                'D-fructose 1,6-bisphosphate = glycerone phosphate + D-glyceraldehyde 3-phosphate',
                                '4.1.2.13');""")

lab.execute("""INSERT INTO enzyme(id,
                                 name,
                                 function,
                                 EC)
                         VALUES(7,
                                'D-glucose-6-phosphate phosphohydrolase',
                                'D-glucose 6-phosphate + H2O = D-glucose + phosphate',
                                '3.1.3.9');""")

lab.execute("""INSERT INTO enzyme(id,
                                 name,
                                 function,
                                 EC)
                         VALUES(8,
                                '2-phospho-D-glycerate hydro-lyase',
                                '2-phospho-D-glycerate = phosphoenolpyruvate + H2O',
                                '4.2.1.11');""")

#### 2.3 Citrate cycle (TCA cycle)
https://www.genome.jp/dbget-bin/www_bget?hsa:5236+hsa:55276
https://www.genome.jp/dbget-bin/www_bget?hsa:226+hsa:229+hsa:230
https://www.genome.jp/dbget-bin/www_bget?ec:2.3.1.61

In [45]:
lab = lab4.cursor()
lab.execute("""INSERT INTO enzyme(id,
                                 name,
                                 function,
                                 EC)
                         VALUES(9,
                                'acetyl-CoA:oxaloacetate C-acetyltransferase',
                                'acetyl-CoA + H2O + oxaloacetate = citrate + CoA',
                                '2.3.3.1');""")

lab.execute("""INSERT INTO enzyme(id,
                                 name,
                                 function,
                                 EC)
                         VALUES(10,
                                '2-oxoglutarate:[dihydrolipoyllysine-residue succinyltransferase]-lipoyllysine 2-oxidoreductase (decarboxylating, acceptor-succinylating)',
                                '2-oxoglutarate + [dihydrolipoyllysine-residue succinyltransferase] lipoyllysine = [dihydrolipoyllysine-residue succinyltransferase] S-succinyldihydrolipoyllysine + CO2',
                                '1.2.4.2');""")

lab.execute("""INSERT INTO enzyme(id,
                                 name,
                                 function,
                                 EC)
                         VALUES(11,
                                'succinyl-CoA:enzyme-N6-(dihydrolipoyl)lysine S-succinyltransferase',
                                'succinyl-CoA + enzyme N6-(dihydrolipoyl)lysine = CoA + enzyme N6-(S-succinyldihydrolipoyl)lysine',
                                '2.3.1.61');""")

lab.execute("""INSERT INTO enzyme(id,
                                 name,
                                 function,
                                 EC)
                         VALUES(12,
                                'succinate:CoA ligase',
                                'GTP + succinate + CoA = GDP + phosphate + succinyl-CoA',
                                '6.2.1.4');""")

### 3.Create a table for pathway

In [46]:
lab = lab4.cursor()

lab.execute("""CREATE TABLE pathway(id INT,
                                name TEXT,
                                description TEXT);""")

In [47]:
lab = lab4.cursor()
lab.execute("""INSERT INTO pathway(id,
                                 name,
                                 description)
                         VALUES(1,
                                'Pentose phosphate pathway',
                                'The pentose phosphate pathway is a process of glucose turnover that produces NADPH as reducing equivalents and pentoses as essential parts of nucleotides.');""")
lab4.commit()

lab.execute("""INSERT INTO pathway(id,
                                 name,
                                 description)
                         VALUES(2,
                                'Glycolysis / Gluconeogenesis',
                                'Glycolysis is the process of converting glucose into pyruvate and generating small amounts of ATP (energy) and NADH (reducing power). It is a central pathway that produces important precursor metabolites: six-carbon compounds of glucose-6P and fructose-6P and three-carbon compounds of glycerone-P, glyceraldehyde-3P, glycerate-3P, phosphoenolpyruvate, and pyruvate');""")
lab4.commit()

lab.execute("""INSERT INTO pathway(id,
                                 name,
                                 description)
                         VALUES(3,
                                'Citrate cycle (TCA cycle)',
                                'The citrate cycle (TCA cycle, Krebs cycle) is an important aerobic pathway for the final steps of the oxidation of carbohydrates and fatty acids. The cycle starts with acetyl-CoA, the activated form of acetate, derived from glycolysis and pyruvate oxidation for carbohydrates and from beta oxidation of fatty acids. The two-carbon acetyl group in acetyl-CoA is transferred to the four-carbon compound of oxaloacetate to form the six-carbon compound of citrate. In a series of reactions two carbons in citrate are oxidized to CO2 and the reaction pathway supplies NADH for use in the oxidative phosphorylation and other metabolic processes. The pathway also supplies important precursor metabolites including 2-oxoglutarate. At the end of the cycle the remaining four-carbon part is transformed back to oxaloacetate. According to the genome sequence data, many organisms seem to lack genes for the full cycle, but contain genes for specific segments.');""")
lab4.commit()

### 4.Create a table for associating genes and enzyme

Associate the ID of **_genes_** table and **_enzyme_** table

In [48]:
lab = lab4.cursor()

lab.execute("""CREATE TABLE gene2enzyme(id INT,
                                enzyme_id INT);""")

In [49]:
lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(1,
                                       1);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(2,
                                       2);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(3,
                                       3);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(4,
                                       4);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(5,
                                       1);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(6,
                                       2);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(7,
                                       3);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(8,
                                       4);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(9,
                                       1);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(10,
                                       2);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(11,
                                       3);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(12,
                                       4);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(13,
                                       5);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(14,
                                       6);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(15,
                                       7);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(16,
                                       7);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(17,
                                       7);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(18,
                                       8);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(19,
                                       5);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(20,
                                       6);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(21,
                                       7);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(22,
                                       8);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(23,
                                       5);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(24,
                                       6);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(25,
                                       8);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(26,
                                       9);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(27,
                                       10);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(28,
                                       10);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(29,
                                       11);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(30,
                                       12);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(31,
                                       9);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(32,
                                       10);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(33,
                                       11);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(34,
                                       12);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(35,
                                       9);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(36,
                                       10);""")

lab.execute("""INSERT INTO gene2enzyme(id,
                                       enzyme_id)
                                VALUES(37,
                                       11);""")

### 5.Create a table for associating enzyme and pathway

Associate the ID of **_pathway_** table and **_enzyme_** table

**Q & A**
**Q1**.There are relationships between enzymes and pathways—some enzymes belong to certain pathways. Do any belong to multiple pathways? Is this a one-to-many or many-to-many relationship?
**A1**
It is definately many-to-many relationship. Pathway is a complex system, many enzymes belong to different pathway, so it is a relationship of many to many.

**Q2** There is an order to enzymes within pathways. How can the order be represented in a table?
**A2**
As far as I can see, the best way is to use order of ID to represent the order of enzyme. The nearer to the entrance of pathway, the lower the number of ID.

**Q3** Genes in the gene table encode enzymes in the enzyme table. How can this be represented? Is this a one-to-one, one-to-many, or many-to-many relationship, and in which direction?
**A3**
It is many to one. Because usually the enzyme has quaternary structure，which means they are made of different monomer proteins produced by different genes. In a word, gene to enzyme is the relationsip of many-to-one.

In [50]:
lab = lab4.cursor()

lab.execute("""CREATE TABLE enzyme2pathway(enzyme_id INT,
                                        pathway_id INT);""")

In [51]:
lab.execute("""INSERT INTO enzyme2pathway(enzyme_id,
                                          pathway_id)
                                VALUES(1,
                                       1);""")

lab.execute("""INSERT INTO enzyme2pathway(enzyme_id,
                                          pathway_id)
                                VALUES(2,
                                       1);""")

lab.execute("""INSERT INTO enzyme2pathway(enzyme_id,
                                          pathway_id)
                                VALUES(3,
                                       1);""")

lab.execute("""INSERT INTO enzyme2pathway(enzyme_id,
                                          pathway_id)
                                VALUES(4,
                                       1);""")

lab.execute("""INSERT INTO enzyme2pathway(enzyme_id,
                                          pathway_id)
                                VALUES(5,
                                       2);""")

lab.execute("""INSERT INTO enzyme2pathway(enzyme_id,
                                          pathway_id)
                                VALUES(6,
                                       2);""")

lab.execute("""INSERT INTO enzyme2pathway(enzyme_id,
                                          pathway_id)
                                VALUES(7,
                                       2);""")

lab.execute("""INSERT INTO enzyme2pathway(enzyme_id,
                                          pathway_id)
                                VALUES(8,
                                       2);""")

lab.execute("""INSERT INTO enzyme2pathway(enzyme_id,
                                          pathway_id)
                                VALUES(9,
                                       3);""")

lab.execute("""INSERT INTO enzyme2pathway(enzyme_id,
                                          pathway_id)
                                VALUES(10,
                                       3);""")

lab.execute("""INSERT INTO enzyme2pathway(enzyme_id,
                                          pathway_id)
                                VALUES(11,
                                       3);""")

lab.execute("""INSERT INTO enzyme2pathway(enzyme_id,
                                          pathway_id)
                                VALUES(12,
                                       3);""")